# AUTO-GENERATED by scripts/gen_genre_registry.exs from the OptimalOS genre
# taxonomy (docs/taxonomy/genres). This is the SINGLE canonical genre registry
# for the engine. 142 genres. Do not edit by hand; regenerate.
[
  %{
    mode: "mixed",
    category: "product",
    genre: "ab-test-plan",
    signal_type: "decide",
    purpose: "Experimental design defining hypothesis, variants, metrics, and success criteria.",
    sections: [
      %{name: "Hypothesis", required: true},
      %{name: "Variants", required: true},
      %{name: "Primary Metric", required: true},
      %{name: "Secondary Metrics", required: false},
      %{name: "Sample Size", required: true},
      %{name: "Duration", required: true},
      %{name: "Decision Criteria", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "design",
    genre: "accessibility-audit",
    signal_type: "inform",
    purpose: "Evaluation of product conformance to WCAG standards with remediation items.",
    sections: [
      %{name: "Scope", required: true},
      %{name: "Standard", required: true},
      %{name: "Methodology", required: true},
      %{name: "Findings", required: true},
      %{name: "Remediation", required: true},
      %{name: "Score", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "marketing",
    genre: "ad-copy",
    signal_type: "direct",
    purpose: "Platform-specific persuasive text driving a defined conversion action.",
    sections: [
      %{name: "Platform", required: true},
      %{name: "Headline", required: true},
      %{name: "Body", required: true},
      %{name: "CTA", required: true},
      %{name: "Variants", required: false},
      %{name: "Targeting", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "adr",
    signal_type: "decide",
    purpose: "Architecture decision record capturing context, decision, and consequences of a significant design choice.",
    sections: [
      %{name: "Status", required: true},
      %{name: "Context", required: true},
      %{name: "Decision", required: true},
      %{name: "Consequences", required: true},
      %{name: "Alternatives", required: true},
      %{name: "References", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "design",
    genre: "animation-spec",
    signal_type: "direct",
    purpose: "Timing, easing, and trigger definitions for motion design elements.",
    sections: [
      %{name: "Element", required: true},
      %{name: "Trigger", required: true},
      %{name: "Duration", required: true},
      %{name: "Easing", required: true},
      %{name: "Properties", required: true},
      %{name: "Reference", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "communication",
    genre: "announcement",
    signal_type: "inform",
    purpose: "Broadcast notification synchronizing a defined population to a change or event.",
    sections: [
      %{name: "What", required: true},
      %{name: "Why", required: true},
      %{name: "Impact", required: true},
      %{name: "Timeline", required: true},
      %{name: "Contact", required: true},
      %{name: "FAQ", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "api-doc",
    signal_type: "inform",
    purpose: "Reference documentation for an API surface enabling integration without source code access.",
    sections: [
      %{name: "Overview", required: true},
      %{name: "Authentication", required: true},
      %{name: "Endpoints", required: true},
      %{name: "Request Schemas", required: true},
      %{name: "Response Schemas", required: true},
      %{name: "Error Codes", required: true},
      %{name: "Rate Limits", required: true},
      %{name: "Code Examples", required: true},
      %{name: "Changelog", required: false},
      %{name: "SDKs / Libraries", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "education",
    genre: "assessment",
    signal_type: "inform",
    purpose: "Evaluation instrument measuring knowledge or skill acquisition.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Learning Outcomes Tested", required: true},
      %{name: "Format", required: true},
      %{name: "Questions", required: true},
      %{name: "Answer Key", required: true},
      %{name: "Passing Score", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "assignment",
    signal_type: "direct",
    purpose: "Defined learning task with instructions, deliverables, and deadline.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Objective", required: true},
      %{name: "Instructions", required: true},
      %{name: "Deliverables", required: true},
      %{name: "Rubric", required: true},
      %{name: "Due Date", required: true},
      %{name: "Resources", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "financial",
    genre: "audit-report",
    signal_type: "inform",
    purpose: "Independent third-party verification of financial statement accuracy.",
    sections: [
      %{name: "Opinion", required: true},
      %{name: "Scope", required: true},
      %{name: "Findings", required: true},
      %{name: "Management Response", required: false},
      %{name: "Recommendations", required: true},
      %{name: "Auditor", required: true}
    ]
  },
  %{
    mode: "data",
    category: "governance",
    genre: "audit-trail",
    signal_type: "inform",
    purpose: "Immutable chronological record of actions for compliance and forensics.",
    sections: [
      %{name: "Action", required: true},
      %{name: "Target", required: true},
      %{name: "Before State", required: false},
      %{name: "After State", required: false}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "balance-sheet",
    signal_type: "inform",
    purpose: "Point-in-time snapshot of assets, liabilities, and equity.",
    sections: [
      %{name: "Date", required: true},
      %{name: "Assets", required: true},
      %{name: "Liabilities", required: true},
      %{name: "Equity", required: true},
      %{name: "Notes", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "sales",
    genre: "battle-card",
    signal_type: "inform",
    purpose: "Competitive positioning enabling reps to win against named competitors.",
    sections: [
      %{name: "Competitor", required: true},
      %{name: "Our Strengths", required: true},
      %{name: "Their Strengths", required: true},
      %{name: "Landmines", required: true},
      %{name: "Common Objections", required: true},
      %{name: "Win Stories", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "marketing",
    genre: "brand-guide",
    signal_type: "direct",
    purpose: "Authoritative rules governing visual identity, voice, and usage.",
    sections: [
      %{name: "Brand Overview", required: true},
      %{name: "Logo Usage", required: true},
      %{name: "Color Palette", required: true},
      %{name: "Typography", required: true},
      %{name: "Voice & Tone", required: true},
      %{name: "Photography", required: false},
      %{name: "Templates", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "business",
    genre: "brief",
    signal_type: "direct",
    purpose: "Short directional document that compels a specific action from a decision-maker.",
    sections: [
      %{name: "Objective", required: true},
      %{name: "Audience", required: true},
      %{name: "Key Messages", required: true},
      %{name: "Call to Action", required: true},
      %{name: "Timeline", required: false},
      %{name: "Supporting Materials", required: false}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "budget",
    signal_type: "direct",
    purpose: "Authorized resource allocation by category for a defined period.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Total Allocation", required: true},
      %{name: "Line Items", required: true},
      %{name: "Approval", required: true},
      %{name: "Variance Threshold", required: true},
      %{name: "Actuals Column", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "support",
    genre: "bug-report",
    signal_type: "inform",
    purpose: "Detailed reproduction case for a software defect submitted for engineering triage.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Environment", required: true},
      %{name: "Steps to Reproduce", required: true},
      %{name: "Expected Behavior", required: true},
      %{name: "Actual Behavior", required: true},
      %{name: "Frequency", required: true},
      %{name: "Workaround", required: false},
      %{name: "Logs/Screenshots", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "governance",
    genre: "business-continuity-plan",
    signal_type: "direct",
    purpose: "Strategy for maintaining operations during and after a major disruption.",
    sections: [
      %{name: "Scope", required: true},
      %{name: "Critical Functions", required: true},
      %{name: "Scenarios", required: true},
      %{name: "Response Procedures", required: true},
      %{name: "Communication Plan", required: true},
      %{name: "Testing Schedule", required: true},
      %{name: "Review Date", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "marketing",
    genre: "campaign-brief",
    signal_type: "direct",
    purpose: "Creative and strategic direction for a marketing initiative.",
    sections: [
      %{name: "Objective", required: true},
      %{name: "Audience", required: true},
      %{name: "Key Message", required: true},
      %{name: "Channels", required: true},
      %{name: "Timeline", required: true},
      %{name: "Creative Direction", required: true},
      %{name: "Success Metrics", required: true},
      %{name: "Budget", required: true}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "cap-table",
    signal_type: "inform",
    purpose: "Definitive record of equity ownership, dilution, and option pool across all holders.",
    sections: [
      %{name: "Company", required: true},
      %{name: "Share Classes", required: true},
      %{name: "Holders", required: true},
      %{name: "Option Pool", required: true},
      %{name: "Round History", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "creative",
    genre: "case-study",
    signal_type: "express",
    purpose: "Client success narrative demonstrating real-world value delivered to build prospect trust and reduce sales friction.",
    sections: [
      %{name: "Client Overview", required: true},
      %{name: "Challenge", required: true},
      %{name: "Solution", required: true},
      %{name: "Implementation", required: false},
      %{name: "Results", required: true},
      %{name: "Quote", required: false},
      %{name: "Why It Worked", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "cease-and-desist",
    signal_type: "direct",
    purpose: "Formal demand to stop a specific activity under threat of legal action.",
    sections: [
      %{name: "Sender Identity", required: true},
      %{name: "Violation", required: true},
      %{name: "Legal Basis", required: true},
      %{name: "Demand", required: true},
      %{name: "Consequences", required: true},
      %{name: "Response Instructions", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "governance",
    genre: "certification-report",
    signal_type: "commit",
    purpose: "Formal evidence package demonstrating compliance for accreditation.",
    sections: [
      %{name: "Standard", required: true},
      %{name: "Scope", required: true},
      %{name: "Controls", required: true},
      %{name: "Gaps", required: true},
      %{name: "Remediation", required: true},
      %{name: "Attestation", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "project",
    genre: "change-request",
    signal_type: "direct",
    purpose: "Formal proposal to modify project scope, timeline, or budget.",
    sections: [
      %{name: "Change Description", required: true},
      %{name: "Reason", required: true},
      %{name: "Impact Analysis", required: true},
      %{name: "Alternatives", required: false},
      %{name: "Recommendation", required: true},
      %{name: "Approval", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "changelog",
    signal_type: "inform",
    purpose: "Version history documenting what changed, why, and for whom across software releases.",
    sections: [
      %{name: "Version + Date", required: true},
      %{name: "Breaking Changes", required: true},
      %{name: "Added", required: true},
      %{name: "Changed", required: false},
      %{name: "Deprecated", required: false},
      %{name: "Removed", required: false},
      %{name: "Fixed", required: false},
      %{name: "Security", required: false}
    ]
  },
  %{
    mode: "data",
    category: "data",
    genre: "cohort-analysis",
    signal_type: "inform",
    purpose: "Behavioral comparison across defined user segments over time.",
    sections: [
      %{name: "Cohort Definition", required: true},
      %{name: "Metric", required: true},
      %{name: "Time Periods", required: true},
      %{name: "Data", required: true},
      %{name: "Findings", required: true},
      %{name: "Recommendations", required: true}
    ]
  },
  %{
    mode: "data",
    category: "people",
    genre: "compensation-plan",
    signal_type: "inform",
    purpose: "Defined structure for base, variable, and equity pay tied to role and performance.",
    sections: [
      %{name: "Role/Level", required: true},
      %{name: "Base Salary", required: true},
      %{name: "Variable", required: true},
      %{name: "Equity", required: false},
      %{name: "Benefits", required: true},
      %{name: "Review Cycle", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "marketing",
    genre: "competitive-analysis",
    signal_type: "inform",
    purpose: "Systematic comparison of competitor positioning, features, and strategy.",
    sections: [
      %{name: "Landscape Overview", required: true},
      %{name: "Competitor Profiles", required: true},
      %{name: "Feature Comparison", required: true},
      %{name: "Pricing Comparison", required: true},
      %{name: "Positioning Gaps", required: true},
      %{name: "Recommendations", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "product",
    genre: "competitive-teardown",
    signal_type: "inform",
    purpose: "Deep feature-by-feature dissection of a competitor product.",
    sections: [
      %{name: "Product", required: true},
      %{name: "Onboarding Experience", required: true},
      %{name: "Core Features", required: true},
      %{name: "UX Assessment", required: true},
      %{name: "Technical Architecture", required: false},
      %{name: "Strategic Implications", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "compliance-report",
    signal_type: "inform",
    purpose: "Evidence-backed attestation that practices meet a specific regulatory standard.",
    sections: [
      %{name: "Standard", required: true},
      %{name: "Scope", required: true},
      %{name: "Control Mapping", required: true},
      %{name: "Gaps", required: true},
      %{name: "Remediation Plan", required: true},
      %{name: "Attestation", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "design",
    genre: "component-spec",
    signal_type: "direct",
    purpose: "Precise behavioral and visual definition of a single UI component.",
    sections: [
      %{name: "Name", required: true},
      %{name: "Purpose", required: true},
      %{name: "Props/API", required: true},
      %{name: "States", required: true},
      %{name: "Variants", required: true},
      %{name: "Accessibility", required: true},
      %{name: "Examples", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "business",
    genre: "contract",
    signal_type: "commit",
    purpose: "Binding agreement between named parties establishing rights, obligations, and remedies.",
    sections: [
      %{name: "Parties", required: true},
      %{name: "Recitals", required: false},
      %{name: "Definitions", required: true},
      %{name: "Scope of Work", required: true},
      %{name: "Obligations", required: true},
      %{name: "Compensation", required: true},
      %{name: "Term and Termination", required: true},
      %{name: "IP and Ownership", required: true},
      %{name: "Limitation of Liability", required: true},
      %{name: "Governing Law", required: true},
      %{name: "Signatures", required: true},
      %{name: "Exhibits", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "curriculum",
    signal_type: "inform",
    purpose: "Master learning architecture defining sequenced modules and outcomes for a course.",
    sections: [
      %{name: "Course Title", required: true},
      %{name: "Learning Outcomes", required: true},
      %{name: "Prerequisites", required: true},
      %{name: "Modules", required: true},
      %{name: "Assessment Strategy", required: true},
      %{name: "Resources", required: true},
      %{name: "Delivery Method", required: true}
    ]
  },
  %{
    mode: "data",
    category: "support",
    genre: "customer-health-scorecard",
    signal_type: "inform",
    purpose: "Composite metric snapshot of account risk, engagement, and expansion potential.",
    sections: [
      %{name: "Account", required: true},
      %{name: "Health Score", required: true},
      %{name: "Usage Metrics", required: true},
      %{name: "Sentiment", required: true},
      %{name: "Risk Factors", required: true},
      %{name: "Action Plan", required: true}
    ]
  },
  %{
    mode: "visual",
    category: "marketing",
    genre: "customer-journey-map",
    signal_type: "inform",
    purpose: "Visual narrative of customer experience from awareness through retention.",
    sections: [
      %{name: "Persona", required: true},
      %{name: "Stages", required: true},
      %{name: "Actions", required: true},
      %{name: "Touchpoints", required: true},
      %{name: "Emotions", required: true},
      %{name: "Pain Points", required: true},
      %{name: "Opportunities", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "data",
    genre: "dashboard-spec",
    signal_type: "direct",
    purpose: "Requirements for a reporting surface defining metrics, visualizations, and data sources.",
    sections: [
      %{name: "Audience", required: true},
      %{name: "Questions Answered", required: true},
      %{name: "Metrics", required: true},
      %{name: "Filters", required: true},
      %{name: "Layout", required: false},
      %{name: "Refresh Rate", required: true},
      %{name: "Access", required: true}
    ]
  },
  %{
    mode: "data",
    category: "data",
    genre: "data-dictionary",
    signal_type: "inform",
    purpose: "Reference catalogue of all data entities, fields, types, and business meanings.",
    sections: [
      %{name: "System", required: true},
      %{name: "Tables", required: true},
      %{name: "Fields", required: true},
      %{name: "Relationships", required: true},
      %{name: "Update Frequency", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "sales",
    genre: "deal-memo",
    signal_type: "inform",
    purpose: "Internal summary of a specific deal's terms and stakeholders for handoff.",
    sections: [
      %{name: "Client", required: true},
      %{name: "Deal Terms", required: true},
      %{name: "Special Conditions", required: true},
      %{name: "Stakeholders", required: true},
      %{name: "Timeline", required: true},
      %{name: "Handoff Notes", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "operational",
    genre: "decision-log",
    signal_type: "decide",
    purpose: "Immutable record of a significant choice with rationale and alternatives, preventing re-litigation.",
    sections: [
      %{name: "Status", required: true},
      %{name: "Context", required: true},
      %{name: "Decision", required: true},
      %{name: "Rationale", required: true},
      %{name: "Consequences", required: true},
      %{name: "Alternatives Considered", required: true},
      %{name: "References", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "design-doc",
    signal_type: "inform",
    purpose: "Pre-implementation exploration of a technical approach for team alignment before coding.",
    sections: [
      %{name: "Problem", required: true},
      %{name: "Proposal", required: true},
      %{name: "Alternatives", required: true},
      %{name: "System Design", required: true},
      %{name: "Trade-offs", required: true},
      %{name: "Open Questions", required: false},
      %{name: "Timeline", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "design",
    genre: "design-system",
    signal_type: "direct",
    purpose: "Authoritative component library governing a product's visual language.",
    sections: [
      %{name: "Design Tokens", required: true},
      %{name: "Components", required: true},
      %{name: "Patterns", required: true},
      %{name: "Accessibility", required: true},
      %{name: "Code Integration", required: true},
      %{name: "Contribution Guide", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "governance",
    genre: "disaster-recovery-plan",
    signal_type: "direct",
    purpose: "Technical procedures for restoring systems and data after catastrophic failure.",
    sections: [
      %{name: "Systems Covered", required: true},
      %{name: "Backup Strategy", required: true},
      %{name: "Recovery Procedures", required: true},
      %{name: "Infrastructure", required: true},
      %{name: "Testing", required: true},
      %{name: "Contacts", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "sales",
    genre: "discovery-notes",
    signal_type: "inform",
    purpose: "Captured prospect pain, context, and qualification data from a sales conversation.",
    sections: [
      %{name: "Prospect", required: true},
      %{name: "Pain Points", required: true},
      %{name: "Current Solution", required: true},
      %{name: "Decision Process", required: true},
      %{name: "Qualification", required: true},
      %{name: "Next Steps", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "communication",
    genre: "email",
    signal_type: "direct",
    purpose: "Asynchronous directed communication to a named recipient requesting action or conveying information.",
    sections: [
      %{name: "Subject", required: true},
      %{name: "Greeting", required: false},
      %{name: "Context", required: false},
      %{name: "Core Payload", required: true},
      %{name: "Next Steps", required: false},
      %{name: "Deadline", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "people",
    genre: "employee-handbook",
    signal_type: "inform",
    purpose: "Comprehensive reference of company policies, culture, and expectations.",
    sections: [
      %{name: "Company Overview", required: true},
      %{name: "Employment Policies", required: true},
      %{name: "Compensation & Benefits", required: true},
      %{name: "Work Expectations", required: true},
      %{name: "Technology & Security", required: true},
      %{name: "Conduct & Discipline", required: true},
      %{name: "Safety", required: true},
      %{name: "Acknowledgment", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "support",
    genre: "escalation",
    signal_type: "direct",
    purpose: "Formal elevation of an unresolved issue to higher authority.",
    sections: [
      %{name: "Issue Summary", required: true},
      %{name: "Customer Impact", required: true},
      %{name: "Timeline", required: true},
      %{name: "What Was Tried", required: true},
      %{name: "Ask", required: true},
      %{name: "Urgency", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "data",
    genre: "etl-spec",
    signal_type: "direct",
    purpose: "Technical design for a data pipeline including source, transformation, and destination.",
    sections: [
      %{name: "Source", required: true},
      %{name: "Transformations", required: true},
      %{name: "Destination", required: true},
      %{name: "Schedule", required: true},
      %{name: "Error Handling", required: true},
      %{name: "Data Quality", required: true},
      %{name: "Dependencies", required: true}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "expense-report",
    signal_type: "direct",
    purpose: "Itemized record of incurred costs submitted for reimbursement.",
    sections: [
      %{name: "Submitter", required: true},
      %{name: "Period", required: true},
      %{name: "Line Items", required: true},
      %{name: "Business Purpose", required: true},
      %{name: "Approval", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "data",
    genre: "experiment-report",
    signal_type: "inform",
    purpose: "Results of a controlled experiment with statistical analysis and recommended action.",
    sections: [
      %{name: "Hypothesis", required: true},
      %{name: "Methodology", required: true},
      %{name: "Results", required: true},
      %{name: "Statistical Significance", required: true},
      %{name: "Practical Significance", required: true},
      %{name: "Recommendation", required: true},
      %{name: "Caveats", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "product",
    genre: "feature-flag-spec",
    signal_type: "direct",
    purpose: "Configuration for a feature toggle including rollout criteria and kill-switch conditions.",
    sections: [
      %{name: "Flag Name", required: true},
      %{name: "Description", required: true},
      %{name: "Rollout Plan", required: true},
      %{name: "Kill Switch", required: true},
      %{name: "Success Criteria", required: true},
      %{name: "Cleanup Date", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "support",
    genre: "feature-request",
    signal_type: "direct",
    purpose: "Proposal for new functionality with use case and impact justification.",
    sections: [
      %{name: "Problem", required: true},
      %{name: "Proposed Solution", required: false},
      %{name: "Use Case", required: true},
      %{name: "Impact", required: true},
      %{name: "Alternatives", required: false},
      %{name: "Priority", required: true}
    ]
  },
  %{
    mode: "data",
    category: "people",
    genre: "feedback-form",
    signal_type: "inform",
    purpose: "Structured prompt for collecting qualitative input from team members or stakeholders.",
    sections: [
      %{name: "Purpose", required: true},
      %{name: "Questions", required: true},
      %{name: "Anonymity", required: true},
      %{name: "Deadline", required: true},
      %{name: "Response Format", required: true}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "financial-forecast",
    signal_type: "inform",
    purpose: "Forward-looking revenue and expense projection for planning and fundraising.",
    sections: [
      %{name: "Forecast Period", required: true},
      %{name: "Assumptions", required: true},
      %{name: "Revenue Projection", required: true},
      %{name: "Expense Projection", required: true},
      %{name: "Cash Flow", required: true},
      %{name: "Scenarios", required: true},
      %{name: "Key Risks", required: false}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "financial-model",
    signal_type: "inform",
    purpose: "Structured numeric model projecting business outcomes under variable assumptions.",
    sections: [
      %{name: "Input Assumptions", required: true},
      %{name: "Revenue Model", required: true},
      %{name: "Cost Model", required: true},
      %{name: "Unit Economics", required: true},
      %{name: "Projections", required: true},
      %{name: "Sensitivity Analysis", required: true},
      %{name: "Methodology Notes", required: false}
    ]
  },
  %{
    mode: "data",
    category: "data",
    genre: "funnel-analysis",
    signal_type: "inform",
    purpose: "Stage-by-stage conversion measurement identifying drop-off points.",
    sections: [
      %{name: "Funnel Definition", required: true},
      %{name: "Overall Conversion", required: true},
      %{name: "Stage-by-Stage", required: true},
      %{name: "Segments", required: true},
      %{name: "Biggest Drop-off", required: true},
      %{name: "Recommendations", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "research",
    genre: "hypothesis",
    signal_type: "decide",
    purpose: "Formal testable prediction derived from observation or theory.",
    sections: [
      %{name: "Hypothesis", required: true},
      %{name: "Evidence", required: true},
      %{name: "Test Design", required: true},
      %{name: "Falsification Criteria", required: true},
      %{name: "Expected Timeline", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "support",
    genre: "incident-report",
    signal_type: "inform",
    purpose: "Summary of a service disruption with timeline and resolution.",
    sections: [
      %{name: "Incident Summary", required: true},
      %{name: "Impact", required: true},
      %{name: "Timeline", required: true},
      %{name: "Root Cause", required: true},
      %{name: "Resolution", required: true},
      %{name: "Prevention", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "governance",
    genre: "incident-response-plan",
    signal_type: "direct",
    purpose: "Pre-defined playbook for containing and recovering from a security or operational incident.",
    sections: [
      %{name: "Scope", required: true},
      %{name: "Roles", required: true},
      %{name: "Detection", required: true},
      %{name: "Containment", required: true},
      %{name: "Eradication", required: true},
      %{name: "Recovery", required: true},
      %{name: "Communication", required: true},
      %{name: "Post-Incident", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "research",
    genre: "interview-guide",
    signal_type: "direct",
    purpose: "Structured question framework for consistent qualitative interviews.",
    sections: [
      %{name: "Research Objective", required: true},
      %{name: "Participant Profile", required: true},
      %{name: "Introduction Script", required: true},
      %{name: "Questions", required: true},
      %{name: "Probes", required: false},
      %{name: "Closing", required: true},
      %{name: "Duration", required: true}
    ]
  },
  %{
    mode: "data",
    category: "business",
    genre: "invoice",
    signal_type: "direct",
    purpose: "Formal financial claim document requesting payment for goods or services rendered.",
    sections: [
      %{name: "Due Date", required: true},
      %{name: "Parties", required: true},
      %{name: "Line Items", required: true},
      %{name: "Subtotal / Tax / Total", required: true},
      %{name: "Payment Methods", required: true},
      %{name: "Purchase Order Reference", required: false},
      %{name: "Notes", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "people",
    genre: "job-posting",
    signal_type: "direct",
    purpose: "Public description of a role attracting qualified candidates.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Company Overview", required: true},
      %{name: "Role Summary", required: true},
      %{name: "Requirements", required: true},
      %{name: "Compensation", required: true},
      %{name: "Location", required: true},
      %{name: "How to Apply", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "support",
    genre: "knowledge-article",
    signal_type: "inform",
    purpose: "Self-service reference resolving a common question without human assistance.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Applies To", required: true},
      %{name: "Answer", required: true},
      %{name: "Related Articles", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "product",
    genre: "launch-checklist",
    signal_type: "direct",
    purpose: "Pre-launch verification ensuring all dependencies are resolved before go-live.",
    sections: [
      %{name: "Launch Date", required: true},
      %{name: "Engineering", required: true},
      %{name: "QA", required: true},
      %{name: "Marketing", required: true},
      %{name: "Support", required: true},
      %{name: "Legal", required: false},
      %{name: "Rollback Plan", required: true},
      %{name: "Sign-offs", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "learning-path",
    signal_type: "direct",
    purpose: "Prescribed sequence of resources enabling a learner to achieve a skill goal.",
    sections: [
      %{name: "Goal", required: true},
      %{name: "Prerequisites", required: true},
      %{name: "Stages", required: true},
      %{name: "Milestones", required: true},
      %{name: "Completion Criteria", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "legal-opinion",
    signal_type: "inform",
    purpose: "Attorney's analysis of legal risk or rights in a specific situation.",
    sections: [
      %{name: "Question Presented", required: true},
      %{name: "Short Answer", required: true},
      %{name: "Facts", required: true},
      %{name: "Analysis", required: true},
      %{name: "Conclusion", required: true},
      %{name: "Caveats", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "lesson-plan",
    signal_type: "direct",
    purpose: "Single-session instructional plan with objectives, activities, and time allocation.",
    sections: [
      %{name: "Session Title", required: true},
      %{name: "Objective", required: true},
      %{name: "Duration", required: true},
      %{name: "Activities", required: true},
      %{name: "Materials", required: true},
      %{name: "Assessment", required: true},
      %{name: "Homework", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "research",
    genre: "literature-review",
    signal_type: "inform",
    purpose: "Synthesized survey of existing research establishing state of knowledge.",
    sections: [
      %{name: "Research Question", required: true},
      %{name: "Methodology", required: true},
      %{name: "Themes", required: true},
      %{name: "Gaps", required: true},
      %{name: "Synthesis", required: true},
      %{name: "References", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "load-test-report",
    signal_type: "inform",
    purpose: "Results of performance testing under simulated load with bottleneck identification.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Test Configuration", required: true},
      %{name: "Results", required: true},
      %{name: "Baseline Comparison", required: true},
      %{name: "Bottlenecks", required: true},
      %{name: "Recommendations", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "marketing",
    genre: "market-research",
    signal_type: "inform",
    purpose: "Synthesized data about target market size, behavior, and trends.",
    sections: [
      %{name: "Research Question", required: true},
      %{name: "Methodology", required: true},
      %{name: "Market Size", required: true},
      %{name: "Trends", required: true},
      %{name: "Customer Insights", required: true},
      %{name: "Implications", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "marketing",
    genre: "media-kit",
    signal_type: "inform",
    purpose: "Package of brand assets and audience data for media partners.",
    sections: [
      %{name: "Company Overview", required: true},
      %{name: "Leadership Bios", required: true},
      %{name: "Brand Assets", required: true},
      %{name: "Audience Data", required: false},
      %{name: "Press Coverage", required: false},
      %{name: "Contact", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "communication",
    genre: "message",
    signal_type: "direct",
    purpose: "Informal asynchronous communication in low-latency channels (Slack, SMS, DM) for quick coordination.",
    sections: [%{name: "Content", required: true}]
  },
  %{
    mode: "linguistic",
    category: "research",
    genre: "methodology",
    signal_type: "inform",
    purpose: "Documented research design specifying how a study will be conducted.",
    sections: [
      %{name: "Research Question", required: true},
      %{name: "Approach", required: true},
      %{name: "Participants", required: true},
      %{name: "Data Collection", required: true},
      %{name: "Analysis Plan", required: true},
      %{name: "Limitations", required: true},
      %{name: "Ethics", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "data",
    genre: "metric-definition",
    signal_type: "inform",
    purpose: "Canonical definition of a business metric including formula, source, and ownership.",
    sections: [
      %{name: "Metric Name", required: true},
      %{name: "Definition", required: true},
      %{name: "Formula", required: true},
      %{name: "Data Source", required: true},
      %{name: "Owner", required: true},
      %{name: "Dimensions", required: false},
      %{name: "Caveats", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "migration-plan",
    signal_type: "direct",
    purpose: "Step-by-step procedure for moving data, infrastructure, or code between states safely.",
    sections: [
      %{name: "Objective", required: true},
      %{name: "Prerequisites", required: true},
      %{name: "Steps", required: true},
      %{name: "Rollback", required: true},
      %{name: "Verification", required: true},
      %{name: "Downtime Window", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "nda",
    signal_type: "commit",
    purpose: "Confidentiality obligation between parties prior to sensitive disclosure.",
    sections: [
      %{name: "Parties", required: true},
      %{name: "Definition of Confidential Information", required: true},
      %{name: "Obligations", required: true},
      %{name: "Exclusions", required: true},
      %{name: "Term", required: true},
      %{name: "Remedies", required: true},
      %{name: "Governing Law", required: true},
      %{name: "Signatures", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "creative",
    genre: "newsletter",
    signal_type: "inform",
    purpose: "Periodic value delivery to a subscribed audience maintaining relationship and driving continued engagement.",
    sections: [
      %{name: "Subject Line", required: true},
      %{name: "Preview Text", required: true},
      %{name: "Opening", required: true},
      %{name: "Primary Content", required: true},
      %{name: "Secondary Items", required: false},
      %{name: "CTA", required: true},
      %{name: "Sign-off", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "communication",
    genre: "note",
    signal_type: "express",
    purpose: "Personal capture of unstructured information, ideas, or observations for later processing.",
    sections: [
      %{name: "Content", required: true},
      %{name: "Tags", required: false},
      %{name: "Next Action", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "sales",
    genre: "objection-handler",
    signal_type: "direct",
    purpose: "Prepared responses to common prospect objections.",
    sections: [
      %{name: "Objection", required: true},
      %{name: "Root Cause", required: true},
      %{name: "Response", required: true},
      %{name: "Proof Point", required: false},
      %{name: "Follow-Up Question", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "people",
    genre: "offer-letter",
    signal_type: "commit",
    purpose: "Formal extension of employment terms to a selected candidate.",
    sections: [
      %{name: "Position", required: true},
      %{name: "Start Date", required: true},
      %{name: "Compensation", required: true},
      %{name: "Benefits", required: true},
      %{name: "Employment Type", required: true},
      %{name: "Conditions", required: false},
      %{name: "Acceptance Deadline", required: true},
      %{name: "Signatures", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "on-call-handoff",
    signal_type: "inform",
    purpose: "Shift-change document conveying active incidents, pending issues, and context to incoming on-call.",
    sections: [
      %{name: "Active Incidents", required: true},
      %{name: "Pending Actions", required: true},
      %{name: "Recent Changes", required: true},
      %{name: "Monitoring Notes", required: false},
      %{name: "Escalation Contacts", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "people",
    genre: "onboarding-doc",
    signal_type: "inform",
    purpose: "Orientation material enabling a new team member to become productive.",
    sections: [
      %{name: "Welcome", required: true},
      %{name: "Day 1 Checklist", required: true},
      %{name: "Week 1 Goals", required: true},
      %{name: "Key People", required: true},
      %{name: "Resources", required: true},
      %{name: "30/60/90 Day Plan", required: false}
    ]
  },
  %{
    mode: "visual",
    category: "people",
    genre: "org-chart",
    signal_type: "inform",
    purpose: "Visual map of reporting relationships and team structure.",
    sections: [
      %{name: "Effective Date", required: true},
      %{name: "Hierarchy", required: true},
      %{name: "Legend", required: true},
      %{name: "Team Descriptions", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "creative",
    genre: "outline",
    signal_type: "inform",
    purpose: "Hierarchical content structure enabling review and alignment before full production.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Thesis", required: true},
      %{name: "Audience", required: true},
      %{name: "Structure", required: true},
      %{name: "Key Points", required: true},
      %{name: "Sources", required: false},
      %{name: "CTA", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "legal",
    genre: "patent-application",
    signal_type: "commit",
    purpose: "Technical and legal disclosure claiming novel invention rights.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Abstract", required: true},
      %{name: "Background", required: true},
      %{name: "Description", required: true},
      %{name: "Claims", required: true},
      %{name: "Drawings", required: true},
      %{name: "Inventor(s)", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "people",
    genre: "performance-review",
    signal_type: "inform",
    purpose: "Structured assessment of an employee's contributions, gaps, and development path.",
    sections: [
      %{name: "Review Period", required: true},
      %{name: "Overall Rating", required: true},
      %{name: "Achievements", required: true},
      %{name: "Development Areas", required: true},
      %{name: "Goals for Next Period", required: true},
      %{name: "Compensation Adjustment", required: false},
      %{name: "Employee Response", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "marketing",
    genre: "persona",
    signal_type: "inform",
    purpose: "Archetypal profile of a target customer segment.",
    sections: [
      %{name: "Name & Photo", required: true},
      %{name: "Demographics", required: true},
      %{name: "Goals", required: true},
      %{name: "Pain Points", required: true},
      %{name: "Behaviors", required: true},
      %{name: "Objections", required: true},
      %{name: "Channels", required: true},
      %{name: "Data Source", required: true}
    ]
  },
  %{
    mode: "data",
    category: "sales",
    genre: "pipeline-report",
    signal_type: "inform",
    purpose: "Stage-by-stage summary of active deals and forecast against quota.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Pipeline Summary", required: true},
      %{name: "Weighted Forecast", required: true},
      %{name: "Quota Attainment", required: true},
      %{name: "Deal Movement", required: true},
      %{name: "Key Deals", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "business",
    genre: "pitch",
    signal_type: "direct",
    purpose: "Persuasive presentation to an external audience (investors, prospects, partners) seeking buy-in or funding.",
    sections: [
      %{name: "Hook", required: true},
      %{name: "Problem", required: true},
      %{name: "Solution", required: true},
      %{name: "Market", required: true},
      %{name: "Traction", required: false},
      %{name: "Business Model", required: true},
      %{name: "Team", required: true},
      %{name: "Ask", required: true},
      %{name: "Use of Funds", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "operational",
    genre: "plan",
    signal_type: "direct",
    purpose: "Forward-looking work breakdown coordinating team execution toward measurable outcomes.",
    sections: [
      %{name: "Objectives", required: true},
      %{name: "Non-Negotiables", required: true},
      %{name: "Tasks", required: true},
      %{name: "Timeline", required: true},
      %{name: "Dependencies", required: true},
      %{name: "Risks", required: true},
      %{name: "Resources", required: false},
      %{name: "Success Metrics", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "governance",
    genre: "policy",
    signal_type: "direct",
    purpose: "Authoritative statement of organizational rules governing a domain of behavior.",
    sections: [
      %{name: "Title", required: true},
      %{name: "Purpose", required: true},
      %{name: "Scope", required: true},
      %{name: "Policy Statement", required: true},
      %{name: "Enforcement", required: true},
      %{name: "Exceptions", required: false},
      %{name: "Owner", required: true},
      %{name: "Effective Date", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "postmortem",
    signal_type: "inform",
    purpose: "Blameless incident analysis identifying root cause, timeline, and systemic improvements.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Timeline", required: true},
      %{name: "Root Cause", required: true},
      %{name: "Contributing Factors", required: false},
      %{name: "Impact", required: true},
      %{name: "Detection", required: true},
      %{name: "Response", required: true},
      %{name: "Action Items", required: true},
      %{name: "Lessons Learned", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "pr-description",
    signal_type: "inform",
    purpose: "Contextual summary of code changes, rationale, and testing enabling efficient code review.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Changes", required: true},
      %{name: "Testing", required: true},
      %{name: "Screenshots", required: false},
      %{name: "Breaking Changes", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "product",
    genre: "prd",
    signal_type: "direct",
    purpose: "Comprehensive statement of what a product or feature must do and why.",
    sections: [
      %{name: "Problem", required: true},
      %{name: "Goals", required: true},
      %{name: "Non-Goals", required: true},
      %{name: "User Stories", required: true},
      %{name: "Requirements", required: true},
      %{name: "Design", required: false},
      %{name: "Technical Considerations", required: false},
      %{name: "Success Metrics", required: true},
      %{name: "Timeline", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "marketing",
    genre: "press-release",
    signal_type: "inform",
    purpose: "Newsworthy announcement distributed to media for earned coverage.",
    sections: [
      %{name: "Headline", required: true},
      %{name: "Dateline", required: true},
      %{name: "Lead", required: true},
      %{name: "Body", required: true},
      %{name: "Quote", required: true},
      %{name: "Boilerplate", required: true},
      %{name: "Contact", required: true}
    ]
  },
  %{
    mode: "data",
    category: "sales",
    genre: "pricing-sheet",
    signal_type: "inform",
    purpose: "Reference of product tiers, prices, and discount thresholds.",
    sections: [
      %{name: "Products/Tiers", required: true},
      %{name: "List Prices", required: true},
      %{name: "Volume Discounts", required: false},
      %{name: "Discount Authority", required: true},
      %{name: "Effective Date", required: true},
      %{name: "Terms", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "privacy-policy",
    signal_type: "inform",
    purpose: "Disclosure of how personal data is collected, used, and protected.",
    sections: [
      %{name: "Data Collected", required: true},
      %{name: "Purpose", required: true},
      %{name: "Sharing", required: true},
      %{name: "Retention", required: true},
      %{name: "User Rights", required: true},
      %{name: "Security", required: true},
      %{name: "Cookies", required: false},
      %{name: "Contact", required: true},
      %{name: "Effective Date", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "governance",
    genre: "procedure",
    signal_type: "direct",
    purpose: "Step-by-step implementation instructions for complying with a policy.",
    sections: [
      %{name: "Related Policy", required: true},
      %{name: "Purpose", required: true},
      %{name: "Steps", required: true},
      %{name: "Records", required: true},
      %{name: "Review Cycle", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "product",
    genre: "product-brief",
    signal_type: "direct",
    purpose: "Concise problem/solution framing before committing to a full PRD.",
    sections: [
      %{name: "Problem", required: true},
      %{name: "Opportunity", required: true},
      %{name: "Proposed Solution", required: true},
      %{name: "Success Criteria", required: true},
      %{name: "Effort Estimate", required: true},
      %{name: "Decision", required: true}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "profit-loss",
    signal_type: "inform",
    purpose: "Period revenue minus expense summary enabling profitability assessment.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Revenue", required: true},
      %{name: "Cost of Goods Sold", required: true},
      %{name: "Operating Expenses", required: true},
      %{name: "Period Comparison", required: true},
      %{name: "Notes", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "project",
    genre: "project-charter",
    signal_type: "commit",
    purpose: "Formal authorization scoping a project, naming its sponsor, and granting resources.",
    sections: [
      %{name: "Project Name", required: true},
      %{name: "Sponsor", required: true},
      %{name: "Problem Statement", required: true},
      %{name: "Objectives", required: true},
      %{name: "Scope", required: true},
      %{name: "Resources", required: true},
      %{name: "Timeline", required: true},
      %{name: "Risks", required: true},
      %{name: "Approvals", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "business",
    genre: "proposal",
    signal_type: "commit",
    purpose: "Formal offer requesting signed commitment from an approver or procurement authority.",
    sections: [
      %{name: "Executive Summary", required: true},
      %{name: "Problem", required: true},
      %{name: "Solution", required: true},
      %{name: "Pricing", required: true},
      %{name: "Timeline", required: true},
      %{name: "Terms", required: true},
      %{name: "Team / Credentials", required: false},
      %{name: "Appendices", required: false}
    ]
  },
  %{
    mode: "data",
    category: "sales",
    genre: "quota-plan",
    signal_type: "direct",
    purpose: "Defined revenue targets per rep, territory, or segment.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Targets", required: true},
      %{name: "Ramp Schedule", required: false},
      %{name: "Accelerators", required: false},
      %{name: "Measurement", required: true},
      %{name: "Payout Schedule", required: true}
    ]
  },
  %{
    mode: "data",
    category: "project",
    genre: "raci-matrix",
    signal_type: "inform",
    purpose: "Role assignment clarifying who is Responsible, Accountable, Consulted, and Informed per task.",
    sections: [
      %{name: "Tasks/Deliverables", required: true},
      %{name: "Roles/People", required: true},
      %{name: "Assignments", required: true},
      %{name: "Legend", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "regulatory-submission",
    signal_type: "commit",
    purpose: "Structured filing to a regulatory body for approval, licensing, or compliance.",
    sections: [
      %{name: "Filing Type", required: true},
      %{name: "Applicant", required: true},
      %{name: "Submission Data", required: true},
      %{name: "Supporting Documents", required: true},
      %{name: "Certifications", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "product",
    genre: "release-notes",
    signal_type: "inform",
    purpose: "User-facing summary of what changed in a release and what it means for them.",
    sections: [
      %{name: "Version", required: true},
      %{name: "Highlights", required: true},
      %{name: "New Features", required: false},
      %{name: "Improvements", required: false},
      %{name: "Bug Fixes", required: false},
      %{name: "Known Issues", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "business",
    genre: "report",
    signal_type: "inform",
    purpose: "Retrospective analysis of data, findings, or events to inform a future decision.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Findings", required: true},
      %{name: "Analysis", required: true},
      %{name: "Recommendations", required: true},
      %{name: "Next Steps", required: true},
      %{name: "Methodology", required: false},
      %{name: "Appendices", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "operational",
    genre: "retrospective",
    signal_type: "decide",
    purpose: "Process improvement reflection at the end of a sprint, project, or period that generates committed action items.",
    sections: [
      %{name: "Went Well", required: true},
      %{name: "Improvement Areas", required: true},
      %{name: "Experiments to Try", required: true},
      %{name: "Action Items", required: true},
      %{name: "Carry-Over Review", required: true},
      %{name: "Team Health", required: false}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "revenue-report",
    signal_type: "inform",
    purpose: "Period-specific breakdown of revenue by source, channel, or segment.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Total Revenue", required: true},
      %{name: "By Segment", required: true},
      %{name: "Recurring vs One-Time", required: true},
      %{name: "Period Comparison", required: true},
      %{name: "Collection Status", required: true},
      %{name: "Trends", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "operational",
    genre: "review",
    signal_type: "express",
    purpose: "Evaluative assessment of an artifact, process, or decision that produces actionable improvement feedback.",
    sections: [
      %{name: "Verdict", required: true},
      %{name: "Summary", required: true},
      %{name: "Critical Issues", required: false},
      %{name: "Major Issues", required: false},
      %{name: "Minor Issues", required: false},
      %{name: "Positive Notes", required: false},
      %{name: "Next Steps", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "rfc",
    signal_type: "decide",
    purpose: "Formal proposal for a significant system change inviting team commentary before adoption.",
    sections: [
      %{name: "Status", required: true},
      %{name: "Summary", required: true},
      %{name: "Motivation", required: true},
      %{name: "Detailed Design", required: true},
      %{name: "Drawbacks", required: true},
      %{name: "Alternatives", required: true},
      %{name: "Unresolved Questions", required: false},
      %{name: "Comment Deadline", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "project",
    genre: "risk-assessment",
    signal_type: "inform",
    purpose: "Identified threats to project objectives with probability, impact, and mitigation.",
    sections: [
      %{name: "Project", required: true},
      %{name: "Risks", required: true},
      %{name: "Risk Matrix", required: true},
      %{name: "Mitigations", required: true},
      %{name: "Residual Risk", required: true},
      %{name: "Review Schedule", required: true}
    ]
  },
  %{
    mode: "data",
    category: "governance",
    genre: "risk-register",
    signal_type: "inform",
    purpose: "Log of identified risks with probability, impact, owner, and mitigation status.",
    sections: [
      %{name: "Description", required: true},
      %{name: "Probability", required: true},
      %{name: "Impact", required: true},
      %{name: "Owner", required: true},
      %{name: "Mitigation", required: true},
      %{name: "Status", required: true}
    ]
  },
  %{
    mode: "visual",
    category: "product",
    genre: "roadmap",
    signal_type: "inform",
    purpose: "Time-horizoned visualization of planned investments and strategic rationale.",
    sections: [
      %{name: "Vision", required: true},
      %{name: "Now", required: true},
      %{name: "Next", required: true},
      %{name: "Later", required: true},
      %{name: "Themes", required: true},
      %{name: "Disclaimer", required: true}
    ]
  },
  %{
    mode: "data",
    category: "education",
    genre: "rubric",
    signal_type: "inform",
    purpose: "Grading criteria specifying performance levels for evaluating work.",
    sections: [
      %{name: "Assignment", required: true},
      %{name: "Criteria", required: true},
      %{name: "Performance Levels", required: true},
      %{name: "Descriptors", required: true},
      %{name: "Weights", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "runbook",
    signal_type: "direct",
    purpose: "Step-by-step operational procedure for executing a known process reliably and safely.",
    sections: [
      %{name: "Purpose", required: true},
      %{name: "Trigger Condition", required: true},
      %{name: "Prerequisites", required: true},
      %{name: "Steps", required: true},
      %{name: "Verification", required: true},
      %{name: "Rollback", required: true},
      %{name: "Escalation", required: false},
      %{name: "References", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "sales",
    genre: "sales-playbook",
    signal_type: "direct",
    purpose: "Consolidated repeatable process for moving deals from discovery to close.",
    sections: [
      %{name: "ICP Definition", required: true},
      %{name: "Sales Stages", required: true},
      %{name: "Messaging", required: true},
      %{name: "Objection Handling", required: true},
      %{name: "Tools & Resources", required: true},
      %{name: "Metrics", required: true}
    ]
  },
  %{
    mode: "code",
    category: "data",
    genre: "schema-migration",
    signal_type: "direct",
    purpose: "Versioned plan for altering database structure with forward and rollback procedures.",
    sections: [
      %{name: "Version", required: true},
      %{name: "Description", required: true},
      %{name: "Up", required: true},
      %{name: "Down", required: true},
      %{name: "Data Impact", required: true},
      %{name: "Prerequisites", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "creative",
    genre: "script",
    signal_type: "direct",
    purpose: "Structured video or audio content with narration, visual direction, and timing for production use.",
    sections: [
      %{name: "Hook (0–30s)", required: true},
      %{name: "Problem", required: true},
      %{name: "Solution", required: true},
      %{name: "Proof", required: false},
      %{name: "CTA", required: true},
      %{name: "B-Roll Notes", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "security-audit",
    signal_type: "inform",
    purpose: "Systematic finding report of vulnerabilities, risks, and remediation priorities.",
    sections: [
      %{name: "Executive Summary", required: true},
      %{name: "Scope", required: true},
      %{name: "Methodology", required: true},
      %{name: "Findings", required: true},
      %{name: "Risk Matrix", required: true},
      %{name: "Remediation Plan", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "people",
    genre: "separation-agreement",
    signal_type: "commit",
    purpose: "Terms governing the end of an employment relationship.",
    sections: [
      %{name: "Parties", required: true},
      %{name: "Separation Date", required: true},
      %{name: "Severance", required: true},
      %{name: "Benefits Continuation", required: true},
      %{name: "Release of Claims", required: true},
      %{name: "Non-Disparagement", required: false},
      %{name: "Return of Property", required: true},
      %{name: "Signatures", required: true}
    ]
  },
  %{
    mode: "data",
    category: "support",
    genre: "sla-report",
    signal_type: "inform",
    purpose: "Periodic measurement of service level adherence against contracted commitments.",
    sections: [
      %{name: "Period", required: true},
      %{name: "SLA Metrics", required: true},
      %{name: "Breaches", required: true},
      %{name: "Credits", required: false},
      %{name: "Trend", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "creative",
    genre: "social-post",
    signal_type: "inform",
    purpose: "Platform-constrained broadcast to reach and engage a public audience through algorithmic and human attention.",
    sections: [
      %{name: "Hook", required: true},
      %{name: "Value", required: true},
      %{name: "CTA", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "technical",
    genre: "spec",
    signal_type: "inform",
    purpose: "Unambiguous technical contract defining requirements, behavior, or architecture for implementers.",
    sections: [
      %{name: "Requirements", required: true},
      %{name: "Acceptance Criteria", required: true},
      %{name: "Architecture", required: true},
      %{name: "API Contracts", required: false},
      %{name: "Dependencies", required: true},
      %{name: "Risks", required: true},
      %{name: "Open Questions", required: false},
      %{name: "Out of Scope", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "project",
    genre: "stakeholder-map",
    signal_type: "inform",
    purpose: "Registry of project stakeholders with influence, interest, and engagement strategy.",
    sections: [
      %{name: "Stakeholders", required: true},
      %{name: "Influence/Interest", required: true},
      %{name: "Engagement Strategy", required: true},
      %{name: "Communication Plan", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "operational",
    genre: "standup",
    signal_type: "inform",
    purpose: "Daily status update creating shared situational awareness and surfacing blockers before they compound.",
    sections: [
      %{name: "Yesterday", required: true},
      %{name: "Today", required: true},
      %{name: "Blockers", required: true},
      %{name: "Flags", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "project",
    genre: "status-report",
    signal_type: "inform",
    purpose: "Periodic update on project health, milestones, risks, and next steps.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Overall Status", required: true},
      %{name: "Milestones", required: true},
      %{name: "Risks & Issues", required: true},
      %{name: "Budget", required: false},
      %{name: "Next Steps", required: true},
      %{name: "Decisions Needed", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "study-guide",
    signal_type: "inform",
    purpose: "Curated summary of key concepts preparing a learner for evaluation.",
    sections: [
      %{name: "Scope", required: true},
      %{name: "Key Concepts", required: true},
      %{name: "Common Mistakes", required: false},
      %{name: "Practice Questions", required: true},
      %{name: "Resources", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "design",
    genre: "style-guide",
    signal_type: "direct",
    purpose: "Voice, tone, and grammar rules governing all written communication.",
    sections: [
      %{name: "Voice", required: true},
      %{name: "Tone", required: true},
      %{name: "Grammar Rules", required: true},
      %{name: "Word List", required: true},
      %{name: "Examples", required: true},
      %{name: "Platform-Specific", required: false}
    ]
  },
  %{
    mode: "data",
    category: "research",
    genre: "survey",
    signal_type: "direct",
    purpose: "Standardized instrument for collecting data from a defined population.",
    sections: [
      %{name: "Purpose", required: true},
      %{name: "Target Population", required: true},
      %{name: "Questions", required: true},
      %{name: "Estimated Duration", required: true},
      %{name: "Distribution Plan", required: true},
      %{name: "Analysis Plan", required: true},
      %{name: "Privacy Notice", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "education",
    genre: "syllabus",
    signal_type: "inform",
    purpose: "Student-facing course contract defining scope, schedule, and expectations.",
    sections: [
      %{name: "Course Info", required: true},
      %{name: "Description", required: true},
      %{name: "Learning Outcomes", required: true},
      %{name: "Schedule", required: true},
      %{name: "Grading", required: true},
      %{name: "Policies", required: true},
      %{name: "Resources", required: true}
    ]
  },
  %{
    mode: "data",
    category: "financial",
    genre: "tax-filing",
    signal_type: "commit",
    purpose: "Required submission of income and liability data to a tax authority.",
    sections: [
      %{name: "Entity", required: true},
      %{name: "Tax Period", required: true},
      %{name: "Income", required: true},
      %{name: "Deductions", required: true},
      %{name: "Payments/Credits", required: true},
      %{name: "Signatures", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "technical",
    genre: "tech-debt-ticket",
    signal_type: "inform",
    purpose: "Documented instance of technical compromise requiring future remediation.",
    sections: [
      %{name: "Description", required: true},
      %{name: "Origin", required: true},
      %{name: "Impact", required: true},
      %{name: "Remediation", required: true},
      %{name: "Priority", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "legal",
    genre: "terms-of-service",
    signal_type: "commit",
    purpose: "Governing rules between a platform and its users at scale.",
    sections: [
      %{name: "Acceptance", required: true},
      %{name: "Service Description", required: true},
      %{name: "User Obligations", required: true},
      %{name: "Payment Terms", required: false},
      %{name: "IP Rights", required: true},
      %{name: "Limitation of Liability", required: true},
      %{name: "Termination", required: true},
      %{name: "Dispute Resolution", required: true},
      %{name: "Modification", required: true},
      %{name: "Governing Law", required: true}
    ]
  },
  %{
    mode: "linguistic",
    category: "support",
    genre: "ticket",
    signal_type: "direct",
    purpose: "Structured record of a customer problem requiring investigation and resolution.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Steps to Reproduce", required: true},
      %{name: "Expected vs Actual", required: true},
      %{name: "Severity", required: true},
      %{name: "Attachments", required: false},
      %{name: "Resolution", required: false}
    ]
  },
  %{
    mode: "mixed",
    category: "legal",
    genre: "trademark-filing",
    signal_type: "commit",
    purpose: "Application to register a brand identifier for exclusive commercial use.",
    sections: [
      %{name: "Mark", required: true},
      %{name: "Classification", required: true},
      %{name: "Goods/Services", required: true},
      %{name: "Applicant", required: true},
      %{name: "Specimen", required: true},
      %{name: "Filing Basis", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "people",
    genre: "training-material",
    signal_type: "direct",
    purpose: "Instructional content enabling a team member to acquire a defined skill.",
    sections: [
      %{name: "Learning Objective", required: true},
      %{name: "Prerequisites", required: true},
      %{name: "Content", required: true},
      %{name: "Exercises", required: true},
      %{name: "Assessment", required: true},
      %{name: "Resources", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "communication",
    genre: "transcript",
    signal_type: "inform",
    purpose: "Verbatim or near-verbatim record of a meeting, interview, or conversation for reference and audit.",
    sections: [
      %{name: "Summary", required: true},
      %{name: "Decisions Made", required: true},
      %{name: "Action Items", required: true},
      %{name: "Full Transcript", required: false},
      %{name: "Recording Link", required: false}
    ]
  },
  %{
    mode: "visual",
    category: "design",
    genre: "user-flow",
    signal_type: "inform",
    purpose: "Annotated path showing how a user moves through a product to complete a goal.",
    sections: [
      %{name: "Goal", required: true},
      %{name: "Entry Point", required: true},
      %{name: "Steps", required: true},
      %{name: "Error Paths", required: true},
      %{name: "Success State", required: true},
      %{name: "Annotations", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "product",
    genre: "user-story",
    signal_type: "direct",
    purpose: "Short narrative capturing a user need from the user's perspective.",
    sections: [
      %{name: "Story", required: true},
      %{name: "Acceptance Criteria", required: true},
      %{name: "Priority", required: true},
      %{name: "Estimate", required: false},
      %{name: "Dependencies", required: false}
    ]
  },
  %{
    mode: "linguistic",
    category: "research",
    genre: "white-paper",
    signal_type: "inform",
    purpose: "Authoritative long-form analysis establishing a position and solution approach.",
    sections: [
      %{name: "Abstract", required: true},
      %{name: "Problem", required: true},
      %{name: "Background", required: true},
      %{name: "Approach", required: true},
      %{name: "Evidence", required: true},
      %{name: "Implications", required: true},
      %{name: "References", required: true}
    ]
  },
  %{
    mode: "mixed",
    category: "sales",
    genre: "win-loss-analysis",
    signal_type: "inform",
    purpose: "Pattern analysis of closed deals identifying why opportunities are won or lost.",
    sections: [
      %{name: "Period", required: true},
      %{name: "Win/Loss Ratio", required: true},
      %{name: "Win Patterns", required: true},
      %{name: "Loss Patterns", required: true},
      %{name: "Competitor Impact", required: true},
      %{name: "Recommendations", required: true}
    ]
  },
  %{
    mode: "visual",
    category: "design",
    genre: "wireframe-spec",
    signal_type: "inform",
    purpose: "Low-fidelity layout blueprint defining information hierarchy and interaction.",
    sections: [
      %{name: "Screen/Flow", required: true},
      %{name: "Layout", required: true},
      %{name: "Interactions", required: true},
      %{name: "Content Notes", required: true},
      %{name: "Annotations", required: false}
    ]
  }
]
