defmodule OptimalEngine.Telemetry.Prometheus do
  @moduledoc """
  Renders a Telemetry snapshot as Prometheus text exposition format (version 0.0.4).

  No external library is required. The format is generated by hand-rolling the
  simple line protocol:

      # HELP <metric_name> <description>
      # TYPE <metric_name> <type>
      <metric_name> <value>

  Metric naming conventions:
  - All metrics are prefixed with `optimal_engine_`.
  - Counter atoms like `:"optimal_engine.intake.ingested"` become
    `optimal_engine_intake_ingested_total`.
  - Histogram atoms like `:"optimal_engine.search.latency_ms"` become
    `optimal_engine_search_latency_ms_count` and `..._sum`.
  - System / DB metrics use their declared name directly.
  """

  alias OptimalEngine.Store
  alias OptimalEngine.Telemetry

  @type render_opts :: []

  # Human-readable descriptions for known counters (keyed by atom name).
  @counter_help %{
    :"optimal_engine.intake.ingested" => "Total contexts ingested",
    :"optimal_engine.intake.rejected" => "Total contexts rejected at intake",
    :"optimal_engine.search.query" => "Total search queries executed",
    :"optimal_engine.retrieval.rag" => "Total RAG retrieval requests",
    :"optimal_engine.connector.run" => "Total connector runs"
  }

  # Human-readable descriptions for known histograms.
  @histogram_help %{
    :"optimal_engine.search.latency_ms" => "Search request latency in milliseconds",
    :"optimal_engine.retrieval.latency_ms" => "RAG retrieval latency in milliseconds",
    :"optimal_engine.connector.latency_ms" => "Connector run latency in milliseconds"
  }

  # ─── public api ──────────────────────────────────────────────────────────────

  @doc """
  Returns the full Prometheus text exposition body as a single string.

  Pulls the current `OptimalEngine.Telemetry.snapshot/0`, appends BEAM system
  metrics (memory, process count) and DB row-count metrics.
  """
  @spec render() :: String.t()
  def render do
    snap = safe_snapshot()

    [
      render_counters(snap.counters),
      render_histograms(snap.histograms),
      render_uptime(snap.uptime_ms),
      render_system_metrics(),
      render_db_metrics()
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n")
    |> then(&(&1 <> "\n"))
  end

  # ─── counter rendering ────────────────────────────────────────────────────────

  defp render_counters(counters) when map_size(counters) == 0, do: ""

  defp render_counters(counters) do
    counters
    |> Enum.sort_by(fn {k, _} -> Atom.to_string(k) end)
    |> Enum.map_join("\n", fn {key, value} ->
      prom_name = counter_name(key)

      help =
        Map.get(@counter_help, key, "Total #{key |> Atom.to_string() |> String.replace(".", " ")}")

      render_metric(prom_name, :counter, help, value)
    end)
  end

  # ─── histogram rendering ──────────────────────────────────────────────────────

  defp render_histograms(histograms) when map_size(histograms) == 0, do: ""

  defp render_histograms(histograms) do
    histograms
    |> Enum.sort_by(fn {k, _} -> Atom.to_string(k) end)
    |> Enum.map_join("\n", fn {key, summary} ->
      base_name = histogram_base_name(key)

      help =
        Map.get(
          @histogram_help,
          key,
          "#{key |> Atom.to_string() |> String.replace(".", " ")} histogram"
        )

      count = Map.get(summary, :count, 0)
      # sum approximation: p50 * count (we don't track raw sum in the aggregator).
      # This is declared so Prometheus has a valid histogram family.
      sum = p50_sum_approx(summary, count)

      render_histogram_family(base_name, help, count, sum)
    end)
  end

  # Approximate sum from p50 * count. Since we store only percentiles (not
  # the running sum), this gives a reasonable Grafana-compatible value for
  # rate/avg queries without adding extra state to the aggregator.
  defp p50_sum_approx(%{p50: p50, count: count}, _count) when count > 0,
    do: p50 * count

  defp p50_sum_approx(_, _count), do: 0

  # ─── uptime ───────────────────────────────────────────────────────────────────

  defp render_uptime(uptime_ms) do
    uptime_s = uptime_ms / 1_000
    render_metric("optimal_engine_uptime_seconds", :gauge, "Engine uptime in seconds", uptime_s)
  end

  # ─── system metrics (BEAM) ────────────────────────────────────────────────────

  defp render_system_metrics do
    heap_bytes = :erlang.memory(:total)
    process_count = :erlang.system_info(:process_count)

    [
      render_metric(
        "optimal_engine_memory_heap_bytes",
        :gauge,
        "Total BEAM VM memory in bytes",
        heap_bytes
      ),
      render_metric(
        "optimal_engine_process_count",
        :gauge,
        "Number of Erlang processes",
        process_count
      )
    ]
    |> Enum.join("\n")
  end

  # ─── database row-count metrics ───────────────────────────────────────────────

  defp render_db_metrics do
    [
      db_count_metric("contexts", "optimal_engine_contexts_total", "Total ingested contexts"),
      db_count_metric("memories", "optimal_engine_memories_total", "Total stored memories"),
      db_count_metric("wiki_pages", "optimal_engine_wiki_pages_total", "Total wiki pages"),
      db_active_workspaces_metric()
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join("\n")
  end

  defp db_count_metric(table, prom_name, help) do
    sql = "SELECT COUNT(*) FROM #{table}"

    case Store.raw_query(sql, []) do
      {:ok, [[count]]} ->
        render_metric(prom_name, :gauge, help, count)

      _ ->
        nil
    end
  end

  defp db_active_workspaces_metric do
    sql = "SELECT COUNT(*) FROM workspaces WHERE status = 'active'"

    case Store.raw_query(sql, []) do
      {:ok, [[count]]} ->
        render_metric(
          "optimal_engine_workspaces_total",
          :gauge,
          "Total active workspaces",
          count
        )

      _ ->
        nil
    end
  end

  # ─── rendering helpers ────────────────────────────────────────────────────────

  # Render a standard scalar metric with HELP + TYPE headers.
  defp render_metric(name, type, help, value) do
    formatted_value = format_value(value)

    """
    # HELP #{name} #{help}
    # TYPE #{name} #{type}
    #{name} #{formatted_value}\
    """
  end

  # Render the _count + _sum pair for a histogram family.
  defp render_histogram_family(base_name, help, count, sum) do
    """
    # HELP #{base_name} #{help}
    # TYPE #{base_name} histogram
    #{base_name}_count #{format_value(count)}
    #{base_name}_sum #{format_value(sum)}\
    """
  end

  # Format numeric values: integers stay integers, floats use up to 6 decimal places.
  defp format_value(v) when is_integer(v), do: Integer.to_string(v)

  defp format_value(v) when is_float(v) do
    # Strip trailing zeros for cleaner output.
    :erlang.float_to_binary(v, decimals: 6)
    |> String.trim_trailing("0")
    |> String.trim_trailing(".")
    |> then(fn s ->
      # Ensure at least one decimal place for gauge values (Prometheus expectation).
      if String.contains?(s, "."), do: s, else: s <> ".0"
    end)
  end

  defp format_value(v), do: to_string(v)

  # ─── name conversion ──────────────────────────────────────────────────────────

  # Converts `:"optimal_engine.intake.ingested"` → `"optimal_engine_intake_ingested_total"`
  defp counter_name(key) do
    key
    |> Atom.to_string()
    |> String.replace(".", "_")
    |> then(&(&1 <> "_total"))
  end

  # Converts `:"optimal_engine.search.latency_ms"` → `"optimal_engine_search_latency_ms"`
  defp histogram_base_name(key) do
    key
    |> Atom.to_string()
    |> String.replace(".", "_")
  end

  # ─── fault tolerance ─────────────────────────────────────────────────────────

  defp safe_snapshot do
    try do
      Telemetry.snapshot()
    rescue
      _ -> %{counters: %{}, histograms: %{}, uptime_ms: 0}
    catch
      :exit, _ -> %{counters: %{}, histograms: %{}, uptime_ms: 0}
    end
  end
end
