defmodule Mix.Tasks.Optimal.RealityCheck do
  @shortdoc "Stress-test every engine layer and report pass / timing / row counts"

  @moduledoc """
  End-to-end reality check — touches every database, every pipeline
  stage, every retrieval path, every compliance workflow. Prints a
  per-probe report with OK / WARN / FAIL + elapsed milliseconds.

  Not a benchmark in the strict sense; it's a *coverage* sweep so you
  can see which layers behave and which break under real usage.

  ## Usage

      mix optimal.reality_check
      mix optimal.reality_check --ingest 50    # extra ingest load
      mix optimal.reality_check --hard         # includes slow paths
  """

  use Mix.Task

  alias OptimalEngine.Architecture
  alias OptimalEngine.Compliance
  alias OptimalEngine.Connectors
  alias OptimalEngine.Health
  alias OptimalEngine.Retrieval
  alias OptimalEngine.Retrieval.Receiver
  alias OptimalEngine.Store
  alias OptimalEngine.Wiki

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {parsed, _, _} =
      OptionParser.parse(args, strict: [ingest: :integer, hard: :boolean])

    ingest_count = Keyword.get(parsed, :ingest, 0)
    hard? = Keyword.get(parsed, :hard, false)

    IO.puts("\n┌─ Optimal Engine — Reality Check ─────────────────────────────┐\n")

    state = %{probes: [], started: System.monotonic_time(:millisecond)}

    state
    |> section("1. Store reality — row counts across every table")
    |> store_counts()
    |> section("2. Health + supervision tree")
    |> health_probes()
    |> section("3. Architecture registry (7 architectures · 6 processors)")
    |> architecture_probes()
    |> section("4. Connector registry (14 adapters)")
    |> connector_probes()
    |> section("5. Wiki tier-3 round-trip")
    |> wiki_probes()
    |> section("6. Retrieval — simple + complex + edge cases")
    |> retrieval_probes()
    |> section("7. Compliance workflows (DSAR, erasure preview, holds)")
    |> compliance_probes()
    |> maybe_section("8. Extra ingest load", ingest_count > 0)
    |> maybe_ingest(ingest_count)
    |> maybe_section("9. Hard paths (slow retrieval, deep joins)", hard?)
    |> maybe_hard(hard?)
    |> summarize()
  end

  # ─── section framing ────────────────────────────────────────────────────

  defp section(state, title) do
    IO.puts("\n  #{title}")
    IO.puts("  " <> String.duplicate("─", 60))
    state
  end

  defp maybe_section(state, _title, false), do: state
  defp maybe_section(state, title, true), do: section(state, title)

  defp maybe_ingest(state, 0), do: state

  defp maybe_ingest(state, n) do
    probe(state, "ingest ×#{n}", fn ->
      for i <- 1..n do
        id = "reality-ingest-#{System.unique_integer([:positive])}-#{i}"

        Store.raw_query(
          """
          INSERT INTO contexts (
            id, tenant_id, uri, type, title, content, genre, node,
            mode, signal_type, format, structure, sn_ratio, entities,
            created_at, modified_at, metadata
          )
          VALUES (?1, 'default', ?2, 'signal', ?3, ?4, 'note',
                  '09-new-stuff', 'linguistic', 'inform', 'markdown',
                  'prose', 0.7, '[]',
                  datetime('now'), datetime('now'), '{"tag":"reality-check"}')
          """,
          [
            id,
            "optimal://reality/#{id}",
            "Reality signal #{i}",
            "Signal number #{i} generated by the reality check load test. Contains entity references to Alice, Bob, and the Core Platform for co-occurrence testing."
          ]
        )
      end

      {:ok, "inserted #{n} rows"}
    end)
  end

  defp maybe_hard(state, false), do: state

  defp maybe_hard(state, true) do
    state
    |> probe("deep entity co-occurrence (3-hop)", fn ->
      sql = """
      SELECT e1.name AS seed, e3.name AS target, COUNT(*) AS cnt
      FROM entities e1
      JOIN entities e2 ON e1.context_id = e2.context_id AND e1.name <> e2.name
      JOIN entities e3 ON e2.context_id = e3.context_id AND e3.name <> e2.name AND e3.name <> e1.name
      GROUP BY e1.name, e3.name
      ORDER BY cnt DESC
      LIMIT 20
      """

      {:ok, rows} = Store.raw_query(sql, [])
      {:ok, "#{length(rows)} 3-hop pairs"}
    end)
    |> probe("chunk hierarchy join (4 scales)", fn ->
      {:ok, rows} =
        Store.raw_query(
          """
          SELECT scale, COUNT(*) AS cnt, AVG(length_bytes) AS avg_len
          FROM chunks GROUP BY scale ORDER BY
            CASE scale
              WHEN 'document' THEN 0 WHEN 'section' THEN 1
              WHEN 'paragraph' THEN 2 WHEN 'sentence' THEN 3
              ELSE 4 END
          """,
          []
        )

      {:ok,
       rows
       |> Enum.map(fn [s, c, l] -> "#{s}:#{c}/#{trunc(l || 0)}b" end)
       |> Enum.join(", ")}
    end)
    |> probe("classifications + intents + clusters triple-join", fn ->
      {:ok, [[n]]} =
        Store.raw_query(
          """
          SELECT COUNT(*) FROM classifications cl
          LEFT JOIN intents i ON i.chunk_id = cl.chunk_id
          LEFT JOIN cluster_members cm ON cm.chunk_id = cl.chunk_id
          """,
          []
        )

      {:ok, "#{n} joined rows"}
    end)
  end

  # ─── probes ─────────────────────────────────────────────────────────────

  defp store_counts(state) do
    tables = [
      "contexts",
      "entities",
      "edges",
      "chunks",
      "classifications",
      "intents",
      "clusters",
      "cluster_members",
      "wiki_pages",
      "citations",
      "events",
      "nodes",
      "node_members",
      "skills",
      "principals",
      "acls",
      "connectors",
      "connector_runs",
      "architectures",
      "processor_runs",
      "retention_policies",
      "legal_holds"
    ]

    Enum.reduce(tables, state, fn t, acc ->
      probe(acc, "rows in #{t}", fn ->
        case Store.raw_query("SELECT COUNT(*) FROM #{t}", []) do
          {:ok, [[n]]} -> {:ok, "#{n}"}
          other -> {:error, inspect(other)}
        end
      end)
    end)
  end

  defp health_probes(state) do
    state
    |> probe("Health.live?", fn -> {:ok, to_string(Health.live?())} end)
    |> probe("Health.status (quick)", fn ->
      r = Health.ready(skip: [:embedder])
      {:ok, "ok?=#{r.ok?} degraded=#{inspect(r.degraded)}"}
    end)
  end

  defp architecture_probes(state) do
    state
    |> probe("Architecture.list()", fn ->
      archs = Architecture.list()
      {:ok, "#{length(archs)} registered"}
    end)
    |> probe("Architecture.fetch(text_signal)", fn ->
      case Architecture.fetch("text_signal") do
        {:ok, arch} -> {:ok, "#{length(arch.fields)} fields, modality=#{arch.modality_primary}"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("ProcessorRegistry.all()", fn ->
      {:ok, "#{length(Architecture.processors())} processors"}
    end)
    |> probe("Architecture.validate(text_signal, sample)", fn ->
      {:ok, arch} = Architecture.fetch("text_signal")

      case Architecture.validate(arch, %{title: "probe", body: "content"}) do
        :ok -> {:ok, "valid data point"}
        {:error, issues} -> {:warn, "validation issues: #{inspect(issues)}"}
      end
    end)
  end

  defp connector_probes(state) do
    state
    |> probe("Connectors.list()", fn ->
      {:ok, "#{length(Connectors.list())} adapters"}
    end)
    |> probe("Connectors.kinds() covers Slack + HubSpot", fn ->
      kinds = Connectors.kinds()

      if :slack in kinds and :hubspot in kinds,
        do: {:ok, "#{length(kinds)} kinds"},
        else: {:error, "missing core adapters"}
    end)
    |> probe("Connectors.credentials_ready? (no key required in dev)", fn ->
      {:ok, to_string(Connectors.credentials_ready?())}
    end)
  end

  defp wiki_probes(state) do
    state
    |> probe("Wiki.list(default tenant)", fn ->
      case Wiki.list("default") do
        {:ok, pages} -> {:ok, "#{length(pages)} pages"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("Wiki.latest(healthtech-pricing-decision)", fn ->
      case Wiki.latest("default", "healthtech-pricing-decision", "default") do
        {:ok, page} -> {:ok, "v#{page.version}, #{byte_size(page.body)} bytes"}
        err -> {:warn, inspect(err)}
      end
    end)
    |> probe("Wiki.verify (integrity on that page)", fn ->
      case Wiki.latest("default", "healthtech-pricing-decision", "default") do
        {:ok, page} ->
          report = Wiki.verify(page)
          {:ok, "ok?=#{report.ok?} issues=#{length(report.issues)}"}

        _ ->
          {:warn, "no page"}
      end
    end)
  end

  defp retrieval_probes(state) do
    receiver = Receiver.new(%{format: :markdown, bandwidth: :medium})

    state
    |> probe("RAG.ask simple ('pricing')", fn ->
      {:ok, res} = Retrieval.ask("pricing", receiver: receiver, skip_intent: true)

      {:ok,
       "source=#{res.source} delivered=#{res.trace.n_delivered} elapsed=#{res.trace.elapsed_ms}ms"}
    end)
    |> probe("RAG.ask complex (long natural query)", fn ->
      q =
        "customer pricing decision Q4 healthtech partner renewal pipeline advanced track curriculum"

      {:ok, res} = Retrieval.ask(q, receiver: receiver, skip_intent: true)

      {:ok,
       "source=#{res.source} delivered=#{res.trace.n_delivered} elapsed=#{res.trace.elapsed_ms}ms"}
    end)
    |> probe("RAG.ask empty query (edge)", fn ->
      {:ok, res} = Retrieval.ask("", receiver: receiver, skip_intent: true, skip_wiki: true)
      {:ok, "source=#{res.source} delivered=#{res.trace.n_delivered}"}
    end)
    |> probe("RAG.ask junk tokens (no-match)", fn ->
      {:ok, res} =
        Retrieval.ask("zzxqyw fnord #{System.unique_integer([:positive])}",
          receiver: receiver,
          skip_intent: true,
          skip_wiki: true
        )

      {:ok, "source=#{res.source} (expected :empty or :chunks)"}
    end)
    |> probe("WikiFirst.lookup_many('healthtech')", fn ->
      pages = Retrieval.WikiFirst.lookup_many("healthtech", "default")
      {:ok, "#{length(pages)} matching pages"}
    end)
    |> probe("direct search → 5 hits, principal=nil", fn ->
      case Retrieval.search("platform", limit: 5) do
        {:ok, hits} -> {:ok, "#{length(hits)} hits"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("receiver bandwidth → token budget math", fn ->
      small = Receiver.new(%{bandwidth: :small})
      large = Receiver.new(%{bandwidth: :large})
      {:ok, "small=#{small.token_budget} large=#{large.token_budget}"}
    end)
  end

  defp compliance_probes(state) do
    # Create a throwaway principal so we don't mutate real data.
    suffix = System.unique_integer([:positive])
    pid = "user:reality-check-#{suffix}@test"

    {:ok, _} =
      OptimalEngine.Identity.Principal.upsert(%{
        id: pid,
        kind: :user,
        display_name: "Reality Check #{suffix}"
      })

    state
    |> probe("Compliance.scan_pii", fn ->
      matches =
        Compliance.scan_pii("Reach me at rc@example.com or 415-555-0100. Card 4532015112830366.")

      {:ok, "#{length(matches)} matches: #{Enum.map_join(matches, ",", & &1.kind)}"}
    end)
    |> probe("Compliance.redact (mask strategy)", fn ->
      report =
        Compliance.redact("Email rc@example.com · SSN 123-45-6789", strategy: :mask)

      {:ok, "#{length(report.matches)} matches, body=#{byte_size(report.redacted)}b"}
    end)
    |> probe("Compliance.dsar_export(#{pid})", fn ->
      case Compliance.dsar_export(pid) do
        {:ok, export} -> {:ok, "#{map_size(export)} sections"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("Compliance.erasure_preview(#{pid})", fn ->
      case Compliance.erasure_preview(pid) do
        {:ok, preview} ->
          {:ok, "counts=#{Enum.map_join(preview.counts, ",", fn {k, v} -> "#{k}:#{v}" end)}"}

        err ->
          {:error, inspect(err)}
      end
    end)
    |> probe("Compliance.active_legal_holds (empty)", fn ->
      holds = Compliance.active_legal_holds("default")
      {:ok, "#{length(holds)} active"}
    end)
    |> probe("Compliance.retention_sweep --dry-run", fn ->
      case Compliance.retention_sweep(dry_run: true) do
        {:ok, result} ->
          {:ok,
           "policies=#{result.policies_evaluated} skipped_held=#{result.skipped_held} errors=#{result.errors}"}

        err ->
          {:error, inspect(err)}
      end
    end)
  end

  # ─── probe harness ──────────────────────────────────────────────────────

  defp probe(state, label, fun) do
    t0 = System.monotonic_time(:millisecond)

    {status, detail} =
      try do
        case fun.() do
          {:ok, d} -> {:ok, d}
          {:warn, d} -> {:warn, d}
          {:error, d} -> {:error, d}
          other -> {:error, inspect(other)}
        end
      rescue
        e -> {:error, "raised: #{Exception.message(e)}"}
      catch
        kind, reason -> {:error, "caught #{kind}: #{inspect(reason)}"}
      end

    elapsed = System.monotonic_time(:millisecond) - t0
    tag = format_tag(status)

    IO.puts("    #{tag}  #{String.pad_trailing(label, 50)} #{format_elapsed(elapsed)} · #{detail}")

    %{state | probes: [{label, status, elapsed, detail} | state.probes]}
  end

  defp format_tag(:ok), do: IO.ANSI.green() <> "OK  " <> IO.ANSI.reset()
  defp format_tag(:warn), do: IO.ANSI.yellow() <> "WARN" <> IO.ANSI.reset()
  defp format_tag(:error), do: IO.ANSI.red() <> "FAIL" <> IO.ANSI.reset()

  defp format_elapsed(ms) do
    str = String.pad_leading("#{ms}ms", 7)

    cond do
      ms < 10 -> IO.ANSI.faint() <> str <> IO.ANSI.reset()
      ms < 200 -> str
      ms < 1000 -> IO.ANSI.yellow() <> str <> IO.ANSI.reset()
      true -> IO.ANSI.red() <> str <> IO.ANSI.reset()
    end
  end

  defp summarize(%{probes: probes, started: t0} = _state) do
    total = System.monotonic_time(:millisecond) - t0
    counts = Enum.frequencies_by(probes, fn {_, s, _, _} -> s end)
    ok = Map.get(counts, :ok, 0)
    warn = Map.get(counts, :warn, 0)
    fail = Map.get(counts, :error, 0)

    slowest =
      probes
      |> Enum.sort_by(fn {_, _, ms, _} -> ms end, :desc)
      |> Enum.take(5)

    IO.puts("\n  ─ Summary " <> String.duplicate("─", 55))
    IO.puts("    total probes: #{length(probes)}   ok: #{ok}   warn: #{warn}   fail: #{fail}")
    IO.puts("    wall-clock:   #{total}ms\n")

    IO.puts("    slowest 5:")

    Enum.each(slowest, fn {label, _s, ms, _d} ->
      IO.puts("      #{format_elapsed(ms)}  #{label}")
    end)

    IO.puts("\n└──────────────────────────────────────────────────────────────┘\n")

    if fail > 0 do
      IO.puts(
        IO.ANSI.red() <> "Reality check: #{fail} failures. See FAIL lines above." <> IO.ANSI.reset()
      )

      System.halt(1)
    end
  end
end
