defmodule Mix.Tasks.Optimal.RealityCheck do
  @shortdoc "Stress-test every engine layer and report pass / timing / row counts"

  @moduledoc """
  End-to-end reality check — touches every database, every pipeline
  stage, every retrieval path, every compliance workflow. Prints a
  per-probe report with OK / WARN / FAIL + elapsed milliseconds.

  Not a benchmark in the strict sense; it's a *coverage* sweep so you
  can see which layers behave and which break under real usage.

  ## Usage

      mix optimal.reality_check
      mix optimal.reality_check --ingest 50    # extra ingest load
      mix optimal.reality_check --hard         # includes slow paths
  """

  use Mix.Task

  alias OptimalEngine.Architecture
  alias OptimalEngine.Compliance
  alias OptimalEngine.Connectors
  alias OptimalEngine.Evaluation
  alias OptimalEngine.Health
  alias OptimalEngine.Identity.Principal
  alias OptimalEngine.MemoryCore.ActiveMemoryPool
  alias OptimalEngine.MemoryCore.ClaimReview
  alias OptimalEngine.MemoryCore.ClaimExtractor
  alias OptimalEngine.MemoryCore.FactPromoter
  alias OptimalEngine.MemoryCore.MemoryObject
  alias OptimalEngine.MemoryCore.RetrievalCoordinator
  alias OptimalEngine.MemoryCore.SourcePackage
  alias OptimalEngine.MemoryCore.Store, as: MemoryCoreStore
  alias OptimalEngine.MemoryCore.ToolModelGovernance
  alias OptimalEngine.MemoryCore.WorkflowSkill
  alias OptimalEngine.Retrieval
  alias OptimalEngine.Retrieval.Receiver
  alias OptimalEngine.Signal.Dispatcher
  alias OptimalEngine.Signal.Envelope, as: Signal
  alias OptimalEngine.Store
  alias OptimalEngine.Wiki.Page
  alias OptimalEngine.WorkspaceExport
  alias OptimalEngine.WorkspaceTopology
  alias OptimalEngine.Wiki

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {parsed, _, _} =
      OptionParser.parse(args, strict: [ingest: :integer, hard: :boolean])

    ingest_count = Keyword.get(parsed, :ingest, 0)
    hard? = Keyword.get(parsed, :hard, false)

    IO.puts("\n┌─ Optimal Engine — Reality Check ─────────────────────────────┐\n")

    cleanup_stale_topology_projection_probe_data()

    state = %{probes: [], started: System.monotonic_time(:millisecond)}

    state
    |> section("1. Store reality — row counts across every table")
    |> store_counts()
    |> section("2. Health + supervision tree")
    |> health_probes()
    |> section("3. Architecture registry (7 architectures · 6 processors)")
    |> architecture_probes()
    |> section("4. Workspace topology + projection spine")
    |> topology_projection_probes()
    |> section("5. Evidence and truth lifecycle")
    |> memory_core_lifecycle_probes()
    |> section("6. Governed recall package")
    |> governed_recall_probes()
    |> section("7. Workflow and Skill Package lifecycle")
    |> workflow_skill_probes()
    |> section("8. Tool and model governance")
    |> tool_model_governance_probes()
    |> section("9. Connector registry (14 adapters)")
    |> connector_probes()
    |> section("10. Evaluation records")
    |> evaluation_probes()
    |> section("11. Wiki tier-3 round-trip")
    |> wiki_probes()
    |> section("12. Retrieval — simple + complex + edge cases")
    |> retrieval_probes()
    |> section("13. Compliance workflows (DSAR, erasure preview, holds)")
    |> compliance_probes()
    |> maybe_section("14. Extra ingest load", ingest_count > 0)
    |> maybe_ingest(ingest_count)
    |> maybe_section("15. Hard paths (slow retrieval, deep joins)", hard?)
    |> maybe_hard(hard?)
    |> summarize()
  end

  # ─── section framing ────────────────────────────────────────────────────

  defp section(state, title) do
    IO.puts("\n  #{title}")
    IO.puts("  " <> String.duplicate("─", 60))
    state
  end

  defp maybe_section(state, _title, false), do: state
  defp maybe_section(state, title, true), do: section(state, title)

  defp maybe_ingest(state, 0), do: state

  defp maybe_ingest(state, n) do
    probe(state, "ingest ×#{n}", fn ->
      for i <- 1..n do
        id = "reality-ingest-#{System.unique_integer([:positive])}-#{i}"

        Store.raw_query(
          """
          INSERT INTO contexts (
            id, tenant_id, uri, type, title, content, genre, node,
            mode, signal_type, format, structure, sn_ratio, entities,
            created_at, modified_at, metadata
          )
          VALUES (?1, 'default', ?2, 'signal', ?3, ?4, 'note',
                  'inbox', 'linguistic', 'inform', 'markdown',
                  'prose', 0.7, '[]',
                  datetime('now'), datetime('now'), '{"tag":"reality-check"}')
          """,
          [
            id,
            "optimal://reality/#{id}",
            "Reality signal #{i}",
            "Signal number #{i} generated by the reality check load test. Contains entity references to Revenue Lead, Operations Lead, and the Core Platform for co-occurrence testing."
          ]
        )
      end

      {:ok, "inserted #{n} rows"}
    end)
  end

  defp maybe_hard(state, false), do: state

  defp maybe_hard(state, true) do
    state
    |> probe("deep entity co-occurrence (3-hop)", fn ->
      sql = """
      SELECT e1.name AS seed, e3.name AS target, COUNT(*) AS cnt
      FROM entities e1
      JOIN entities e2 ON e1.context_id = e2.context_id AND e1.name <> e2.name
      JOIN entities e3 ON e2.context_id = e3.context_id AND e3.name <> e2.name AND e3.name <> e1.name
      GROUP BY e1.name, e3.name
      ORDER BY cnt DESC
      LIMIT 20
      """

      {:ok, rows} = Store.raw_query(sql, [])
      {:ok, "#{length(rows)} 3-hop pairs"}
    end)
    |> probe("chunk hierarchy join (4 scales)", fn ->
      {:ok, rows} =
        Store.raw_query(
          """
          SELECT scale, COUNT(*) AS cnt, AVG(length_bytes) AS avg_len
          FROM chunks GROUP BY scale ORDER BY
            CASE scale
              WHEN 'document' THEN 0 WHEN 'section' THEN 1
              WHEN 'paragraph' THEN 2 WHEN 'sentence' THEN 3
              ELSE 4 END
          """,
          []
        )

      {:ok,
       rows
       |> Enum.map(fn [s, c, l] -> "#{s}:#{c}/#{trunc(l || 0)}b" end)
       |> Enum.join(", ")}
    end)
    |> probe("classifications + intents + clusters triple-join", fn ->
      {:ok, [[n]]} =
        Store.raw_query(
          """
          SELECT COUNT(*) FROM classifications cl
          LEFT JOIN intents i ON i.chunk_id = cl.chunk_id
          LEFT JOIN cluster_members cm ON cm.chunk_id = cl.chunk_id
          """,
          []
        )

      {:ok, "#{n} joined rows"}
    end)
  end

  defp cleanup_stale_topology_projection_probe_data do
    stale_workspace_sql = [
      "DELETE FROM link_health_records WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM projection_revisions WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM export_records WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM derivation_ledger WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM source_packages WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM topology_change_requests WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM node_members WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM node_relationships WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM nodes WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM node_types WHERE workspace_id LIKE 'default:reality-workspace-%'",
      "DELETE FROM workspaces WHERE id LIKE 'default:reality-workspace-%'",
      "DELETE FROM principals WHERE id = 'principal:reality-agent'"
    ]

    Enum.each(stale_workspace_sql, fn sql -> Store.raw_execute(sql, []) end)
  end

  # ─── probes ─────────────────────────────────────────────────────────────

  defp store_counts(state) do
    tables = [
      "contexts",
      "entities",
      "edges",
      "chunks",
      "classifications",
      "intents",
      "clusters",
      "cluster_members",
      "wiki_pages",
      "citations",
      "events",
      "nodes",
      "node_types",
      "node_relationships",
      "node_members",
      "topology_change_requests",
      "export_records",
      "projection_revisions",
      "link_health_records",
      "source_packages",
      "assets",
      "asset_adapter_runs",
      "asset_extractions",
      "asset_transcripts",
      "asset_ocr_spans",
      "asset_visual_observations",
      "asset_embedding_refs",
      "claims",
      "facts",
      "memory_objects",
      "relationship_edges",
      "derivation_ledger",
      "context_packages",
      "active_memory_pools",
      "model_call_operations",
      "mcp_tool_definitions",
      "model_call_runs",
      "tool_call_runs",
      "workflow_traces",
      "generalized_workflows",
      "procedural_memory_objects",
      "skill_packages",
      "evaluation_runs",
      "evaluation_cases",
      "skills",
      "principals",
      "acls",
      "connectors",
      "connector_runs",
      "architectures",
      "processor_runs",
      "retention_policies",
      "legal_holds"
    ]

    Enum.reduce(tables, state, fn t, acc ->
      probe(acc, "rows in #{t}", fn ->
        case Store.raw_query("SELECT COUNT(*) FROM #{t}", []) do
          {:ok, [[n]]} -> {:ok, "#{n}"}
          other -> {:error, inspect(other)}
        end
      end)
    end)
  end

  defp topology_projection_probes(state) do
    suffix = System.unique_integer([:positive])
    workspace_slug = "reality-workspace-#{suffix}"
    tmp_root = Path.join(System.tmp_dir!(), workspace_slug)
    previous_root = Application.get_env(:optimal_engine, :root_path)
    Application.put_env(:optimal_engine, :root_path, tmp_root)

    seed =
      with {:ok, workspace} <-
             WorkspaceTopology.create_workspace(%{
               slug: workspace_slug,
               name: "Reality Workspace #{suffix}",
               description: "Throwaway workspace created by the reality check"
             }),
           {:ok, entity} <-
             WorkspaceTopology.create_node(%{
               workspace_id: workspace.id,
               slug: "entity",
               name: "Entity",
               kind: :entity
             }),
           {:ok, department} <-
             WorkspaceTopology.create_node(%{
               workspace_id: workspace.id,
               slug: "department",
               name: "Department",
               kind: :department,
               parent_id: entity.id
             }),
           {:ok, project} <-
             WorkspaceTopology.create_node(%{
               workspace_id: workspace.id,
               slug: "project",
               name: "Project",
               kind: :project,
               parent_id: department.id
             }),
           {:ok, relationship} <-
             WorkspaceTopology.link_nodes(project.id, entity.id, :depends_on,
               workspace_id: workspace.id
             ),
           {:ok, agent} <-
             Principal.upsert(%{
               id: "principal:reality-agent",
               kind: :agent,
               display_name: "Reality Check Agent"
             }),
           :ok <-
             WorkspaceTopology.add_node_member(project.id, agent.id,
               workspace_id: workspace.id,
               membership: :observer,
               role: "agent"
             ),
           {:ok, export} <-
             WorkspaceExport.record_export(%{
               workspace_id: workspace.id,
               source_object_type: "node",
               source_object_id: project.id,
               surface_type: "markdown",
               destination_uri: "file://nodes/project/context.md",
               generated_by: "reality_check"
             }),
           {:ok, projection} <-
             WorkspaceExport.record_projection_revision(export.id, %{
               workspace_id: workspace.id,
               projection_uri: export.destination_uri,
               content: "# Project\n\nReality check projection.",
               source_object_links: [%{type: "node", id: project.id}]
             }) do
        {:ok,
         %{
           workspace: workspace,
           entity: entity,
           department: department,
           project: project,
           agent: agent,
           relationship: relationship,
           export: export,
           projection: projection
         }}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("workspace has standard node types", fn ->
            {:ok, types} = WorkspaceTopology.list_node_types(workspace_id: ctx.workspace.id)
            slugs = MapSet.new(Enum.map(types, & &1.slug))

            if MapSet.subset?(MapSet.new(["entity", "project", "person", "operation"]), slugs),
              do: {:ok, "#{MapSet.size(slugs)} node types"},
              else: {:error, "missing standard node types: #{inspect(MapSet.to_list(slugs))}"}
          end)
          |> probe("workspace-scoped node tree", fn ->
            {:ok, [root]} = WorkspaceTopology.node_tree(workspace_id: ctx.workspace.id)
            [department] = root.children
            [project] = department.children

            if root.node.id == ctx.entity.id and project.node.id == ctx.project.id,
              do: {:ok, "entity -> department -> project"},
              else: {:error, "unexpected tree shape"}
          end)
          |> probe("typed node relationship", fn ->
            {:ok, outgoing} =
              WorkspaceTopology.relationships_for_node(ctx.project.id,
                workspace_id: ctx.workspace.id,
                direction: :outgoing
              )

            if Enum.any?(outgoing, &(&1.id == ctx.relationship.id)),
              do: {:ok, "#{length(outgoing)} outgoing relationship(s)"},
              else: {:error, "relationship not found"}
          end)
          |> probe("workspace-scoped node membership", fn ->
            {:ok, members} =
              WorkspaceTopology.node_members(ctx.project.id, workspace_id: ctx.workspace.id)

            if Enum.any?(members, &(&1.principal_id == ctx.agent.id)),
              do: {:ok, "#{length(members)} member(s)"},
              else: {:error, "member not found"}
          end)
          |> probe("projection drift detection", fn ->
            case WorkspaceExport.detect_drift(
                   ctx.export.id,
                   "# Project\n\nReality check projection."
                 ) do
              {:ok, :fresh} -> {:ok, "fresh"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("projection invalidation", fn ->
            case WorkspaceExport.invalidate_for_node(ctx.project.id,
                   workspace_id: ctx.workspace.id,
                   reason: "reality check node change"
                 ) do
              {:ok, %{export_record_ids: [_], projection_revision_count: 1}} ->
                {:ok, "marked stale"}

              other ->
                {:error, inspect(other)}
            end
          end)
          |> probe("projection edit re-enters source evidence", fn ->
            case WorkspaceExport.capture_edit(ctx.export.id, %{
                   content: "Reality check edit returned through the workspace surface.",
                   actor_id: "human:reality-check"
                 }) do
              {:ok, capture} ->
                {:ok, "source=#{capture.source_package.id}"}

              other ->
                {:error, inspect(other)}
            end
          end)

        {:error, reason} ->
          probe(state, "workspace topology seed", fn -> {:error, inspect(reason)} end)
      end

    cleanup_topology_projection_probe(seed)
    restore_root_path(previous_root)
    File.rm_rf(tmp_root)
    state
  end

  defp cleanup_topology_projection_probe({:ok, %{workspace: %{id: workspace_id}, agent: agent}}) do
    cleanup_sql = [
      {"link_health_records", "DELETE FROM link_health_records WHERE workspace_id = ?1"},
      {"projection_revisions", "DELETE FROM projection_revisions WHERE workspace_id = ?1"},
      {"export_records", "DELETE FROM export_records WHERE workspace_id = ?1"},
      {"derivation_ledger", "DELETE FROM derivation_ledger WHERE workspace_id = ?1"},
      {"source_packages", "DELETE FROM source_packages WHERE workspace_id = ?1"},
      {"topology_change_requests", "DELETE FROM topology_change_requests WHERE workspace_id = ?1"},
      {"node_members", "DELETE FROM node_members WHERE workspace_id = ?1"},
      {"node_relationships", "DELETE FROM node_relationships WHERE workspace_id = ?1"},
      {"nodes", "DELETE FROM nodes WHERE workspace_id = ?1"},
      {"node_types", "DELETE FROM node_types WHERE workspace_id = ?1"},
      {"workspaces", "DELETE FROM workspaces WHERE id = ?1"}
    ]

    Enum.each(cleanup_sql, fn {_table, sql} -> Store.raw_execute(sql, [workspace_id]) end)
    Store.raw_execute("DELETE FROM principals WHERE id = ?1", [agent.id])
  end

  defp cleanup_topology_projection_probe(_), do: :ok

  defp restore_root_path(nil), do: Application.delete_env(:optimal_engine, :root_path)

  defp restore_root_path(previous_root),
    do: Application.put_env(:optimal_engine, :root_path, previous_root)

  defp memory_core_lifecycle_probes(state) do
    suffix = System.unique_integer([:positive])
    workspace_id = "default:reality-memory-core-#{suffix}"

    source =
      SourcePackage.from_text("Reality check source: the project launch was approved.",
        workspace_id: workspace_id,
        source_type: "reality_check",
        source_class: "text",
        trust_label: "unreviewed",
        security_labels: ["internal"],
        partition_ids: ["reality-check"]
      )

    seed =
      with {:ok, claim} <-
             ClaimExtractor.extract_from_source(source,
               claim_text: "The source states that the project launch was approved.",
               subject_anchor: "project_launch",
               action_class: "approved",
               object_anchor: "reality_check_source",
               aggregate_confidence: 0.72,
               aggregate_precision: 0.68,
               actor_id: "agent:reality-check"
             ),
           {:ok, fact} <-
             FactPromoter.promote(claim,
               fact_text: "The project launch was approved.",
               verifier_id: "human:reality-check",
               aggregate_confidence: 0.91,
               aggregate_precision: 0.86
             ),
           {:ok, memory} <-
             MemoryObject.build_from_fact(fact,
               summary: "Reality check accepted memory: project launch approval is source-backed.",
               memory_type: "decision",
               salience: 0.8
             ) do
        {:ok, %{source: source, claim: claim, fact: fact, memory: memory}}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("source package preserved", fn ->
            count_for("source_packages", workspace_id, ctx.source.id)
          end)
          |> probe("claim remains separate from truth", fn ->
            count_for("claims", workspace_id, ctx.claim.id)
          end)
          |> probe("fact promotion writes accepted fact", fn ->
            count_for("facts", workspace_id, ctx.fact.id)
          end)
          |> probe("memory object wraps accepted fact", fn ->
            count_for("memory_objects", workspace_id, ctx.memory.id)
          end)
          |> probe("evidence edges and ledger entries", fn ->
            with {:ok, [[edges]]} <-
                   Store.raw_query(
                     "SELECT COUNT(*) FROM relationship_edges WHERE workspace_id = ?1 AND relationship_type = 'supports'",
                     [workspace_id]
                   ),
                 {:ok, [[ledger]]} <-
                   Store.raw_query(
                     "SELECT COUNT(*) FROM derivation_ledger WHERE workspace_id = ?1",
                     [workspace_id]
                   ) do
              if edges >= 3 and ledger >= 3,
                do: {:ok, "edges=#{edges} ledger=#{ledger}"},
                else: {:error, "edges=#{edges} ledger=#{ledger}"}
            else
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("fact supersession policy closes replaced fact", fn ->
            replacement_source =
              SourcePackage.from_text(
                "Reality check source: the project launch approval was replaced.",
                workspace_id: workspace_id,
                source_type: "reality_check",
                source_class: "text",
                trust_label: "reviewed",
                security_labels: ["internal"],
                partition_ids: ["reality-check"]
              )

            with {:ok, replacement_claim} <-
                   ClaimExtractor.extract_from_source(replacement_source,
                     claim_text: "The source states that launch approval was replaced.",
                     subject_anchor: "project_launch",
                     action_class: "approved",
                     object_anchor: "reality_check_source",
                     aggregate_confidence: 0.74,
                     aggregate_precision: 0.7,
                     actor_id: "agent:reality-check"
                   ),
                 {:ok, pre_supersession_package} <-
                   RetrievalCoordinator.retrieve("launch",
                     workspace_id: workspace_id,
                     actor_id: "agent:reality-check",
                     allowed_partitions: ["reality-check"],
                     allowed_security_labels: ["internal"]
                   ),
                 {:ok, replacement} <-
                   ClaimReview.promote(replacement_claim.id,
                     workspace_id: workspace_id,
                     actor_id: "human:reality-check",
                     fact_text: "The project launch approval was replaced.",
                     supersedes_fact_id: ctx.fact.id,
                     supersession_reason: "reality check replacement source"
                   ),
                 {:ok, [["superseded", "superseded"]]} <-
                   Store.raw_query(
                     "SELECT lifecycle_state, contradiction_status FROM facts WHERE workspace_id = ?1 AND id = ?2",
                     [workspace_id, ctx.fact.id]
                   ),
                 {:ok, [[1]]} <-
                   Store.raw_query(
                     "SELECT COUNT(*) FROM relationship_edges WHERE workspace_id = ?1 AND relationship_type = 'supersedes' AND from_object_id = ?2 AND to_object_id = ?3",
                     [workspace_id, replacement.fact.id, ctx.fact.id]
                   ),
                 {:ok, [["superseded", "superseded"]]} <-
                   Store.raw_query(
                     "SELECT lifecycle_state, supersession_status FROM memory_objects WHERE workspace_id = ?1 AND id = ?2",
                     [workspace_id, ctx.memory.id]
                   ),
                 {:ok, [["stale"]]} <-
                   Store.raw_query(
                     "SELECT refresh_state FROM context_packages WHERE workspace_id = ?1 AND id = ?2",
                     [workspace_id, pre_supersession_package.id]
                   ) do
              {:ok, "superseded=#{ctx.fact.id}"}
            else
              other -> {:error, inspect(other)}
            end
          end)

        {:error, reason} ->
          probe(state, "memory lifecycle seed", fn -> {:error, inspect(reason)} end)
      end

    cleanup_memory_core_lifecycle_probe(workspace_id)
    state
  end

  defp count_for(table, workspace_id, id) do
    case Store.raw_query("SELECT COUNT(*) FROM #{table} WHERE workspace_id = ?1 AND id = ?2", [
           workspace_id,
           id
         ]) do
      {:ok, [[1]]} -> {:ok, "stored"}
      {:ok, [[count]]} -> {:error, "expected 1 row, got #{count}"}
      other -> {:error, inspect(other)}
    end
  end

  defp cleanup_memory_core_lifecycle_probe(workspace_id) do
    [
      "DELETE FROM derivation_ledger WHERE workspace_id = ?1",
      "DELETE FROM relationship_edges WHERE workspace_id = ?1",
      "DELETE FROM memory_objects WHERE workspace_id = ?1",
      "DELETE FROM facts WHERE workspace_id = ?1",
      "DELETE FROM claims WHERE workspace_id = ?1",
      "DELETE FROM source_packages WHERE workspace_id = ?1"
    ]
    |> Enum.each(&Store.raw_execute(&1, [workspace_id]))
  end

  defp governed_recall_probes(state) do
    suffix = System.unique_integer([:positive])
    workspace_id = "default:reality-recall-#{suffix}"

    seed =
      with {:ok, _ctx} <- seed_memory_for_recall(workspace_id, ["reality-check"]),
           {:ok, package} <-
             RetrievalCoordinator.retrieve("launch",
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               allowed_partitions: ["reality-check"],
               allowed_security_labels: ["internal"]
             ),
           {:ok, filtered_package} <-
             RetrievalCoordinator.retrieve("launch",
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               allowed_partitions: ["different-partition"],
               allowed_security_labels: ["internal"]
             ),
           {:ok, batch_package} <-
             RetrievalCoordinator.retrieve("launch",
               workspace_id: workspace_id,
               request_id: "reality-batch-refresh",
               actor_id: "agent:reality-check",
               allowed_partitions: ["reality-check"],
               allowed_security_labels: ["internal"]
             ),
           [%{id: fact_id}] = package.fact_links,
           :ok <-
             MemoryCoreStore.invalidate_context_packages_for_object("fact", fact_id,
               workspace_id: workspace_id,
               reason: "reality_refresh_probe"
             ),
           {:ok, refreshed_package} <-
             RetrievalCoordinator.refresh_context_package(package.id, workspace_id: workspace_id),
           {:ok, batch_refresh} <-
             RetrievalCoordinator.refresh_stale_context_packages(workspace_id: workspace_id) do
        {:ok,
         %{
           package: package,
           filtered_package: filtered_package,
           batch_package: batch_package,
           batch_refresh: batch_refresh,
           refreshed_package: refreshed_package
         }}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("context package assembled", fn ->
            if length(ctx.package.fact_links) == 1 and length(ctx.package.memory_links) == 1,
              do: {:ok, "facts=1 memories=1"},
              else: {:error, inspect(ctx.package.filtered_object_summary)}
          end)
          |> probe("context package persisted", fn ->
            case Store.raw_query(
                   "SELECT COUNT(*) FROM context_packages WHERE workspace_id = ?1 AND id = ?2",
                   [workspace_id, ctx.package.id]
                 ) do
              {:ok, [[1]]} -> {:ok, "stored"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("authorization filters before package assembly", fn ->
            summary = ctx.filtered_package.filtered_object_summary

            if summary.redacted_or_filtered_objects == 2 and ctx.filtered_package.fact_links == [] do
              {:ok, "filtered=#{summary.redacted_or_filtered_objects}"}
            else
              {:error, inspect(summary)}
            end
          end)
          |> probe("stale context package refreshed", fn ->
            if ctx.refreshed_package.id != ctx.package.id and
                 ctx.refreshed_package.refresh_state == "fresh" and
                 ctx.refreshed_package.fact_links == ctx.package.fact_links do
              {:ok, "fresh=#{ctx.refreshed_package.id}"}
            else
              {:error, inspect(ctx.refreshed_package)}
            end
          end)
          |> probe("stale context package batch refreshed", fn ->
            case ctx.batch_refresh do
              %{
                stale_context_package_ids: stale_ids,
                refreshed_context_packages: refreshed_packages,
                errors: []
              }
              when is_list(stale_ids) and is_list(refreshed_packages) ->
                refreshed_package =
                  Enum.find(refreshed_packages, &(Map.get(&1, :refresh_state) == "fresh"))

                if stale_ids != [] and not is_nil(refreshed_package) do
                  {:ok, "refreshed=#{length(refreshed_packages)}"}
                else
                  {:error, inspect(ctx.batch_refresh)}
                end

              other ->
                {:error, inspect(other)}
            end
          end)

        {:error, reason} ->
          probe(state, "governed recall seed", fn -> {:error, inspect(reason)} end)
      end

    cleanup_governed_recall_probe(workspace_id)
    state
  end

  defp seed_memory_for_recall(workspace_id, partition_ids) do
    source =
      SourcePackage.from_text("Reality recall source: the project launch was approved.",
        workspace_id: workspace_id,
        source_type: "reality_check",
        source_class: "text",
        trust_label: "unreviewed",
        security_labels: ["internal"],
        partition_ids: partition_ids
      )

    with {:ok, claim} <-
           ClaimExtractor.extract_from_source(source,
             claim_text: "The source states that the project launch was approved.",
             subject_anchor: "project_launch",
             action_class: "approved",
             object_anchor: "reality_recall_source",
             aggregate_confidence: 0.72,
             aggregate_precision: 0.68,
             actor_id: "agent:reality-check"
           ),
         {:ok, fact} <-
           FactPromoter.promote(claim,
             fact_text: "The project launch was approved.",
             verifier_id: "human:reality-check",
             aggregate_confidence: 0.91,
             aggregate_precision: 0.86
           ),
         {:ok, memory} <-
           MemoryObject.build_from_fact(fact,
             summary: "Reality check accepted memory: project launch approval is source-backed.",
             memory_type: "decision",
             salience: 0.8
           ) do
      {:ok, %{source: source, claim: claim, fact: fact, memory: memory}}
    end
  end

  defp cleanup_governed_recall_probe(workspace_id) do
    [
      "DELETE FROM context_packages WHERE workspace_id = ?1",
      "DELETE FROM derivation_ledger WHERE workspace_id = ?1",
      "DELETE FROM relationship_edges WHERE workspace_id = ?1",
      "DELETE FROM memory_objects WHERE workspace_id = ?1",
      "DELETE FROM facts WHERE workspace_id = ?1",
      "DELETE FROM claims WHERE workspace_id = ?1",
      "DELETE FROM source_packages WHERE workspace_id = ?1"
    ]
    |> Enum.each(&Store.raw_execute(&1, [workspace_id]))
  end

  defp workflow_skill_probes(state) do
    suffix = System.unique_integer([:positive])
    workspace_id = "default:reality-workflow-skill-#{suffix}"

    seed =
      with {:ok, memory_ctx} <- seed_memory_for_recall(workspace_id, ["reality-check"]),
           {:ok, pool} <-
             ActiveMemoryPool.open(
               workspace_id: workspace_id,
               task_type: "launch_review",
               subject_anchor: "project_launch",
               member_links: [%{type: "human", id: "human:reviewer"}],
               agent_links: [%{type: "agent", id: "agent:reality-check"}],
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ),
           {:ok, package} <-
             RetrievalCoordinator.retrieve("launch",
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               active_memory_pool_id: pool.id,
               allowed_partitions: ["reality-check"],
               allowed_security_labels: ["internal"]
             ),
           {:ok, _loaded_pool} <- ActiveMemoryPool.load_context_package(pool.id, package),
           :ok <-
             MemoryCoreStore.invalidate_context_packages_for_object("fact", memory_ctx.fact.id,
               workspace_id: workspace_id,
               reason: "pool_refresh_probe"
             ),
           {:ok, pool_refresh} <- ActiveMemoryPool.refresh_context_packages(pool.id),
           {:ok, _observation} <-
             ActiveMemoryPool.publish_observation(
               pool.id,
               "Reality workflow observed that launch review produced a budget follow-up.",
               actor_id: "agent:reality-check",
               claim_text: "Launch review produced a budget follow-up.",
               subject_anchor: "project_launch",
               action_class: "reviewed",
               object_anchor: "budget_follow_up"
             ),
           {:ok, trace} <-
             WorkflowSkill.capture_trace_from_pool(pool.id,
               workflow_family: "launch_review",
               action_class: "reviewed",
               outcome: "budget_follow_up_recorded",
               step_links: [
                 %{type: "step", id: "load_context"},
                 %{type: "step", id: "record_observation"}
               ],
               actor_id: "agent:reality-check"
             ),
           {:ok, workflow} <-
             WorkflowSkill.generalize_workflow(trace,
               applicability_conditions: %{node_type: "project"},
               validation_score: 0.35,
               actor_id: "agent:reality-check"
             ),
           {:ok, procedure} <-
             WorkflowSkill.create_procedural_memory(workflow,
               capability_name: "launch_review_procedure",
               required_privileges: ["memory:read", "claims:create"],
               actor_id: "agent:reality-check"
             ),
           {:ok, skill} <-
             WorkflowSkill.package_skill(procedure,
               skill_package_name: "launch_review_skill",
               input_contract: %{requires: ["project_node_id"]},
               output_contract: %{creates: ["pending_claims"]},
               execution_policy: %{requires_review: true},
               actor_id: "agent:reality-check"
             ),
           {:ok, approved_skill} <-
             WorkflowSkill.package_skill(procedure,
               skill_package_name: "launch_review_approved_skill",
               review_status: "approved",
               enabled_state: "enabled",
               input_contract: %{requires: ["project_node_id"]},
               output_contract: %{creates: ["pending_claims"]},
               execution_policy: %{requires_review: true},
               actor_id: "agent:reality-check"
             ),
           {:ok, workflow_skill_package} <-
             RetrievalCoordinator.retrieve("launch_review",
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               allowed_partitions: ["reality-check"],
               allowed_security_labels: ["internal"],
               workflow_family: "launch_review",
               task_family: "launch_review"
             ) do
        {:ok,
         %{
           pool: pool,
           pool_refresh: pool_refresh,
           trace: trace,
           workflow: workflow,
           procedure: procedure,
           skill: skill,
           approved_skill: approved_skill,
           workflow_skill_package: workflow_skill_package
         }}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("active pool opened for workflow work", fn ->
            count_for("active_memory_pools", workspace_id, ctx.pool.id)
          end)
          |> probe("active pool refreshed stale context", fn ->
            case ctx.pool_refresh.refreshed_context_packages do
              [%{refresh_state: "fresh"}] -> {:ok, "refreshed=1"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("workflow trace captured from pool", fn ->
            count_for("workflow_traces", workspace_id, ctx.trace.id)
          end)
          |> probe("generalized workflow candidate stored", fn ->
            count_for("generalized_workflows", workspace_id, ctx.workflow.id)
          end)
          |> probe("procedural memory object stored", fn ->
            count_for("procedural_memory_objects", workspace_id, ctx.procedure.id)
          end)
          |> probe("skill package remains draft and disabled", fn ->
            case Store.raw_query(
                   """
                   SELECT review_status, enabled_state
                   FROM skill_packages
                   WHERE workspace_id = ?1 AND id = ?2
                   """,
                   [workspace_id, ctx.skill.id]
                 ) do
              {:ok, [["draft", "disabled"]]} -> {:ok, "draft/disabled"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("retrieval packages workflow and approved skill", fn ->
            package = ctx.workflow_skill_package

            cond do
              package.workflow_links != [%{type: "generalized_workflow", id: ctx.workflow.id}] ->
                {:error, "missing workflow link"}

              package.skill_package_links != [%{type: "skill_package", id: ctx.approved_skill.id}] ->
                {:error, "missing approved skill link"}

              package.filtered_object_summary.returned_skill_packages != 1 ->
                {:error, "unexpected returned skill count"}

              true ->
                {:ok, "workflows=1 approved_skills=1"}
            end
          end)
          |> probe("workflow-skill derivation ledger", fn ->
            case Store.raw_query(
                   """
                   SELECT COUNT(*)
                   FROM derivation_ledger
                   WHERE workspace_id = ?1
                     AND activity_type IN (
                       'memory_core.capture_workflow_trace',
                       'memory_core.generalize_workflow',
                       'memory_core.create_procedural_memory',
                       'memory_core.package_skill'
                     )
                   """,
                   [workspace_id]
                 ) do
              {:ok, [[5]]} -> {:ok, "5 lifecycle entries"}
              other -> {:error, inspect(other)}
            end
          end)

        {:error, reason} ->
          probe(state, "workflow-skill seed", fn -> {:error, inspect(reason)} end)
      end

    cleanup_workflow_skill_probe(workspace_id)
    state
  end

  defp cleanup_workflow_skill_probe(workspace_id) do
    [
      "DELETE FROM skill_packages WHERE workspace_id = ?1",
      "DELETE FROM procedural_memory_objects WHERE workspace_id = ?1",
      "DELETE FROM generalized_workflows WHERE workspace_id = ?1",
      "DELETE FROM workflow_traces WHERE workspace_id = ?1",
      "DELETE FROM active_memory_pools WHERE workspace_id = ?1",
      "DELETE FROM context_packages WHERE workspace_id = ?1",
      "DELETE FROM derivation_ledger WHERE workspace_id = ?1",
      "DELETE FROM relationship_edges WHERE workspace_id = ?1",
      "DELETE FROM memory_objects WHERE workspace_id = ?1",
      "DELETE FROM facts WHERE workspace_id = ?1",
      "DELETE FROM claims WHERE workspace_id = ?1",
      "DELETE FROM source_packages WHERE workspace_id = ?1"
    ]
    |> Enum.each(&Store.raw_execute(&1, [workspace_id]))
  end

  defp tool_model_governance_probes(state) do
    suffix = System.unique_integer([:positive])
    workspace_id = "default:reality-tool-model-#{suffix}"

    seed =
      with {:ok, pool} <-
             ActiveMemoryPool.open(
               workspace_id: workspace_id,
               task_type: "tool_model_review",
               subject_anchor: "project_launch",
               agent_links: [%{type: "agent", id: "agent:reality-check"}],
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ),
           {:ok, tool_definition} <-
             ToolModelGovernance.register_mcp_tool_definition(
               workspace_id: workspace_id,
               tool_name: "calendar.read",
               implementation_type: "external_connector",
               required_privileges: ["calendar:read"],
               allowed_partitions: ["reality-check"],
               input_schema: %{required: ["calendar_id"]},
               output_schema: %{required: ["events"]},
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ),
           {:ok, dispatch_tool_definition} <-
             ToolModelGovernance.register_mcp_tool_definition(
               workspace_id: workspace_id,
               tool_name: "signal.dispatch",
               implementation_type: "signal_adapter",
               required_privileges: ["signal:deliver"],
               allowed_partitions: ["reality-check"],
               input_schema: %{required: ["signal_type"]},
               output_schema: %{required: ["delivered"]},
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ),
           {:ok, model_operation} <-
             ToolModelGovernance.register_model_call_operation(
               workspace_id: workspace_id,
               function_name: "summarize_context",
               model_task_type: "summarization",
               model_id: "reality-model",
               required_privileges: ["model:summarize"],
               allowed_partitions: ["reality-check"],
               input_schema: %{required: ["context"]},
               output_contract: %{required: ["summary"]},
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ),
           {:ok, rejected_tool_run} <-
             ToolModelGovernance.record_tool_call(
               "calendar.read",
               %{calendar_id: "primary"},
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: [],
               requested_partitions: ["reality-check"]
             ),
           {:ok, invalid_tool_output_run} <-
             ToolModelGovernance.record_tool_call(
               "calendar.read",
               %{calendar_id: "primary"},
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               active_memory_pool_id: pool.id,
               granted_privileges: ["calendar:read"],
               requested_partitions: ["reality-check"],
               output_payload: %{},
               observation_text: "Calendar tool returned an invalid empty payload.",
               claim_text: "Calendar returned an invalid empty payload."
             ),
           {:ok, allowed_tool_run} <-
             ToolModelGovernance.record_tool_call(
               "calendar.read",
               %{calendar_id: "primary"},
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               active_memory_pool_id: pool.id,
               granted_privileges: ["calendar:read"],
               requested_partitions: ["reality-check"],
               output_payload: %{events: [%{title: "Launch review"}]},
               observation_text: "Calendar tool returned a launch review event.",
               claim_text: "Calendar contains a launch review event.",
               subject_anchor: "project_launch",
               action_class: "scheduled",
               object_anchor: "launch_review_event"
             ),
           {:ok, allowed_model_run} <-
             ToolModelGovernance.record_model_call(
               "summarize_context",
               %{context: "Launch context"},
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["model:summarize"],
               requested_partitions: ["reality-check"],
               output_payload: %{summary: "Launch is ready for review."}
             ),
           {:ok, invalid_model_output_run} <-
             ToolModelGovernance.record_model_call(
               "summarize_context",
               %{context: "Launch context"},
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["model:summarize"],
               requested_partitions: ["reality-check"],
               output_payload: %{}
             ),
           {:error, {:rejected, blocked_execution_run}} <-
             ToolModelGovernance.execute_tool_call(
               "signal.dispatch",
               %{signal_type: "reality.blocked"},
               fn _payload ->
                 send(self(), :governed_executor_should_not_run)
                 {:ok, %{delivered: true}}
               end,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: [],
               requested_partitions: ["reality-check"]
             ),
           {:ok, allowed_execution_run} <-
             ToolModelGovernance.execute_tool_call(
               "signal.dispatch",
               %{signal_type: "reality.allowed"},
               fn _payload -> {:ok, %{delivered: true}} end,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["signal:deliver"],
               requested_partitions: ["reality-check"]
             ),
           {:error, {:execution_failed, :boom, failed_execution_run}} <-
             ToolModelGovernance.execute_tool_call(
               "signal.dispatch",
               %{signal_type: "reality.failed"},
               fn _payload -> {:error, :boom} end,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["signal:deliver"],
               requested_partitions: ["reality-check"]
             ),
           signal = Signal.new!("reality.dispatch", source: "/reality-check"),
           {:ok, []} <-
             Dispatcher.dispatch(signal,
               handlers: [],
               adapter: :governed,
               adapter_opts: [
                 tool_name: "signal.dispatch",
                 inner_adapter: :noop,
                 input_payload: %{signal_type: signal.type},
                 governance_opts: [
                   workspace_id: workspace_id,
                   actor_id: "agent:reality-check",
                   granted_privileges: ["signal:deliver"],
                   requested_partitions: ["reality-check"]
                 ]
               ]
             ) do
        {:ok,
         %{
           pool: pool,
           tool_definition: tool_definition,
           dispatch_tool_definition: dispatch_tool_definition,
           model_operation: model_operation,
           rejected_tool_run: rejected_tool_run,
           invalid_tool_output_run: invalid_tool_output_run,
           allowed_tool_run: allowed_tool_run,
           allowed_model_run: allowed_model_run,
           invalid_model_output_run: invalid_model_output_run,
           blocked_execution_run: blocked_execution_run,
           allowed_execution_run: allowed_execution_run,
           failed_execution_run: failed_execution_run
         }}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("tool definition registered", fn ->
            count_for("mcp_tool_definitions", workspace_id, ctx.tool_definition.id)
          end)
          |> probe("model operation registered", fn ->
            count_for("model_call_operations", workspace_id, ctx.model_operation.id)
          end)
          |> probe("tool call rejection recorded", fn ->
            if ctx.rejected_tool_run.decision_state == "rejected" and
                 String.contains?(ctx.rejected_tool_run.rejection_reason, "calendar:read") do
              {:ok, "rejected with missing privilege"}
            else
              {:error, inspect(ctx.rejected_tool_run)}
            end
          end)
          |> probe("allowed tool call recorded", fn ->
            case Store.raw_query(
                   """
                   SELECT COUNT(*)
                   FROM tool_call_runs
                   WHERE workspace_id = ?1
                     AND mcp_tool_definition_id = ?2
                     AND decision_state = 'allowed'
                     AND run_status = 'completed'
                   """,
                   [workspace_id, ctx.tool_definition.id]
                 ) do
              {:ok, [[1]]} -> {:ok, "stored"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("invalid tool output quarantined", fn ->
            if ctx.invalid_tool_output_run.run_status == "output_rejected" and
                 String.contains?(
                   ctx.invalid_tool_output_run.rejection_reason,
                   "missing_output:events"
                 ) and
                 ctx.invalid_tool_output_run.observation_links == [] do
              {:ok, "missing output rejected without observation"}
            else
              {:error, inspect(ctx.invalid_tool_output_run)}
            end
          end)
          |> probe("tool output becomes pending claim", fn ->
            case ctx.allowed_tool_run.observation_links do
              [%{type: "claim", id: claim_id}] ->
                count_for("claims", workspace_id, claim_id)

              other ->
                {:error, inspect(other)}
            end
          end)
          |> probe("allowed model call recorded", fn ->
            case Store.raw_query(
                   """
                   SELECT COUNT(*)
                   FROM model_call_runs
                   WHERE workspace_id = ?1
                     AND model_call_operation_id = ?2
                     AND decision_state = 'allowed'
                     AND run_status = 'completed'
                   """,
                   [workspace_id, ctx.model_operation.id]
                 ) do
              {:ok, [[1]]} -> {:ok, "stored"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("invalid model output quarantined", fn ->
            if ctx.invalid_model_output_run.run_status == "output_rejected" and
                 String.contains?(
                   ctx.invalid_model_output_run.rejection_reason,
                   "missing_output:summary"
                 ) and
                 ctx.invalid_model_output_run.observation_links == [] do
              {:ok, "missing output rejected without observation"}
            else
              {:error, inspect(ctx.invalid_model_output_run)}
            end
          end)
          |> probe("governed call run audit links attached", fn ->
            runs = [
              ctx.rejected_tool_run,
              ctx.invalid_tool_output_run,
              ctx.allowed_tool_run,
              ctx.allowed_model_run,
              ctx.invalid_model_output_run
            ]

            if Enum.all?(runs, &match?([%{type: "audit_event"}], &1.audit_event_links)) do
              {:ok, "#{length(runs)} run audit link(s)"}
            else
              {:error, inspect(Enum.map(runs, & &1.audit_event_links))}
            end
          end)
          |> probe("governed call audit emitted", fn ->
            case Store.raw_query(
                   """
                   SELECT COUNT(*)
                   FROM events
                   WHERE tenant_id = 'default'
                     AND principal = 'agent:reality-check'
                     AND kind IN ('tool.call.governed', 'model.call.governed')
                     AND metadata LIKE ?1
                   """,
                   ["%#{workspace_id}%"]
                 ) do
              {:ok, [[count]]} when count >= 2 -> {:ok, "#{count} audit event(s)"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("governed execution blocks executor", fn ->
            blocked? =
              ctx.blocked_execution_run.decision_state == "rejected" and
                String.contains?(ctx.blocked_execution_run.rejection_reason, "signal:deliver")

            receive do
              :governed_executor_should_not_run ->
                {:error, "executor ran despite rejected governance decision"}
            after
              0 ->
                if blocked?, do: {:ok, "blocked before execution"}, else: {:error, "not blocked"}
            end
          end)
          |> probe("governed execution records completed run", fn ->
            if ctx.allowed_execution_run.decision_state == "allowed" and
                 ctx.allowed_execution_run.run_status == "completed" do
              {:ok, "completed execution recorded"}
            else
              {:error, inspect(ctx.allowed_execution_run)}
            end
          end)
          |> probe("governed execution records failures", fn ->
            if ctx.failed_execution_run.decision_state == "allowed" and
                 ctx.failed_execution_run.run_status == "failed" and
                 String.contains?(ctx.failed_execution_run.rejection_reason, "execution_failed") do
              {:ok, "failed execution recorded"}
            else
              {:error, inspect(ctx.failed_execution_run)}
            end
          end)
          |> probe("dispatcher governed adapter records delivery", fn ->
            case Store.raw_query(
                   """
                   SELECT COUNT(*)
                   FROM tool_call_runs
                   WHERE workspace_id = ?1
                     AND mcp_tool_definition_id = ?2
                     AND tool_name = 'signal.dispatch'
                     AND decision_state = 'allowed'
                     AND run_status = 'completed'
                   """,
                   [workspace_id, ctx.dispatch_tool_definition.id]
                 ) do
              {:ok, [[count]]} when count >= 2 -> {:ok, "#{count} completed dispatch run(s)"}
              other -> {:error, inspect(other)}
            end
          end)

        {:error, reason} ->
          probe(state, "tool/model governance seed", fn -> {:error, inspect(reason)} end)
      end

    cleanup_tool_model_governance_probe(workspace_id)
    state
  end

  defp cleanup_tool_model_governance_probe(workspace_id) do
    [
      "DELETE FROM model_call_runs WHERE workspace_id = ?1",
      "DELETE FROM tool_call_runs WHERE workspace_id = ?1",
      "DELETE FROM model_call_operations WHERE workspace_id = ?1",
      "DELETE FROM mcp_tool_definitions WHERE workspace_id = ?1",
      "DELETE FROM active_memory_pools WHERE workspace_id = ?1",
      "DELETE FROM derivation_ledger WHERE workspace_id = ?1",
      "DELETE FROM claims WHERE workspace_id = ?1",
      "DELETE FROM source_packages WHERE workspace_id = ?1"
    ]
    |> Enum.each(&Store.raw_execute(&1, [workspace_id]))
  end

  defp health_probes(state) do
    state
    |> probe("Health.live?", fn -> {:ok, to_string(Health.live?())} end)
    |> probe("Health.status (quick)", fn ->
      r = Health.ready(skip: [:embedder])
      {:ok, "ok?=#{r.ok?} degraded=#{inspect(r.degraded)}"}
    end)
  end

  defp architecture_probes(state) do
    state
    |> probe("Architecture.list()", fn ->
      archs = Architecture.list()
      {:ok, "#{length(archs)} registered"}
    end)
    |> probe("Architecture.fetch(text_signal)", fn ->
      case Architecture.fetch("text_signal") do
        {:ok, arch} -> {:ok, "#{length(arch.fields)} fields, modality=#{arch.modality_primary}"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("ProcessorRegistry.all()", fn ->
      {:ok, "#{length(Architecture.processors())} processors"}
    end)
    |> probe("Architecture.validate(text_signal, sample)", fn ->
      {:ok, arch} = Architecture.fetch("text_signal")

      case Architecture.validate(arch, %{title: "probe", body: "content"}) do
        :ok -> {:ok, "valid data point"}
        {:error, issues} -> {:warn, "validation issues: #{inspect(issues)}"}
      end
    end)
  end

  defp connector_probes(state) do
    suffix = System.unique_integer([:positive])
    connector_id = "reality-slack-#{suffix}"
    workspace_id = "default:reality-connector-#{suffix}"

    {:ok, _} =
      Connectors.register(%{
        id: connector_id,
        kind: :slack,
        config: %{
          "workspace_id" => "T01",
          "channels" => ["C01"],
          "credentials" => %{"bot_token" => "xoxb-reality"}
        }
      })

    state =
      state
      |> probe("Connectors.list()", fn ->
        {:ok, "#{length(Connectors.list())} adapters"}
      end)
      |> probe("Connectors.kinds() covers Slack + HubSpot", fn ->
        kinds = Connectors.kinds()

        if :slack in kinds and :hubspot in kinds,
          do: {:ok, "#{length(kinds)} kinds"},
          else: {:error, "missing core adapters"}
      end)
      |> probe("Connectors.credentials_ready? (no key required in dev)", fn ->
        {:ok, to_string(Connectors.credentials_ready?())}
      end)
      |> probe("connector governance blocks runner without grants", fn ->
        case Connectors.run_governed(connector_id,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: [],
               requested_partitions: ["reality-check"],
               allowed_partitions: ["reality-check"]
             ) do
          {:error, {:rejected, run}} ->
            with {:ok, [[connector_runs]]} <-
                   Store.raw_query(
                     "SELECT COUNT(*) FROM connector_runs WHERE connector_id = ?1",
                     [connector_id]
                   ) do
              if connector_runs == 0 and run.run_status == "rejected" do
                {:ok, "rejected before connector run"}
              else
                {:error, "connector_runs=#{connector_runs} run_status=#{run.run_status}"}
              end
            end

          other ->
            {:error, inspect(other)}
        end
      end)
      |> probe("connector governance allows sync runner", fn ->
        case Connectors.run_governed(connector_id,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["connector:slack:sync", "signal:ingest"],
               requested_partitions: ["reality-check"],
               allowed_partitions: ["reality-check"]
             ) do
          {:ok, result} ->
            run = result.governance_run

            if run.decision_state == "allowed" and run.run_status == "completed" and
                 result.connector_result.status in ["success", "error"] do
              {:ok, "governed #{run.tool_name}, connector status=#{result.connector_result.status}"}
            else
              {:error, inspect(result)}
            end

          other ->
            {:error, inspect(other)}
        end
      end)
      |> probe("connector governed run writes both audit layers", fn ->
        with {:ok, [[connector_runs]]} <-
               Store.raw_query(
                 "SELECT COUNT(*) FROM connector_runs WHERE connector_id = ?1",
                 [connector_id]
               ),
             {:ok, [[tool_runs]]} <-
               Store.raw_query(
                 """
                 SELECT COUNT(*)
                 FROM tool_call_runs
                 WHERE workspace_id = ?1
                   AND tool_name = 'connector.slack.sync'
                   AND decision_state = 'allowed'
                   AND run_status = 'completed'
                 """,
                 [workspace_id]
               ) do
          if connector_runs == 1 and tool_runs == 1 do
            {:ok, "connector_runs=#{connector_runs}, tool_call_runs=#{tool_runs}"}
          else
            {:error, "connector_runs=#{connector_runs}, tool_call_runs=#{tool_runs}"}
          end
        end
      end)
      |> probe("connector governed audit event emitted", fn ->
        case Store.raw_query(
               """
               SELECT COUNT(*)
               FROM events
               WHERE tenant_id = 'default'
                 AND principal = 'agent:reality-check'
                 AND kind = 'tool.call.governed'
                 AND metadata LIKE ?1
               """,
               ["%#{workspace_id}%"]
             ) do
          {:ok, [[count]]} when count >= 2 -> {:ok, "#{count} audit event(s)"}
          other -> {:error, inspect(other)}
        end
      end)
      |> probe("connector sync payload preserves assets", fn ->
        case Connectors.run(connector_id,
               adapter_resolver: fn "slack" ->
                 {:ok, Mix.Tasks.Optimal.RealityCheck.ConnectorAssetAdapter}
               end,
               workspace_id: workspace_id,
               actor_id: "agent:reality-check",
               granted_privileges: ["connector:slack:sync", "signal:ingest"],
               requested_partitions: ["reality-check"],
               allowed_partitions: ["reality-check"],
               security_labels: ["internal"],
               partition_ids: ["reality-check"]
             ) do
          {:ok, result} ->
            connector_result = result.connector_result

            with {:ok, [[asset_count]]} <-
                   Store.raw_query(
                     "SELECT COUNT(*) FROM assets WHERE workspace_id = ?1 AND metadata LIKE ?2",
                     [workspace_id, "%reality-file-1%"]
                   ) do
              if result.governance_run.decision_state == "allowed" and
                   connector_result.status == "success" and connector_result.assets == 1 and
                   connector_result.asset_errors == 0 and asset_count == 1 do
                {:ok,
                 "assets=#{connector_result.assets}, asset_errors=#{connector_result.asset_errors}"}
              else
                {:error, "result=#{inspect(result)} asset_count=#{asset_count}"}
              end
            end

          other ->
            {:error, inspect(other)}
        end
      end)

    cleanup_connector_probe(connector_id, workspace_id)
    state
  end

  defp cleanup_connector_probe(connector_id, workspace_id) do
    [
      {"DELETE FROM connector_runs WHERE connector_id = ?1", [connector_id]},
      {"DELETE FROM connectors WHERE id = ?1", [connector_id]},
      {"DELETE FROM tool_call_runs WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM mcp_tool_definitions WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM assets WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM source_packages WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM derivation_ledger WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM events WHERE metadata LIKE ?1", ["%#{workspace_id}%"]}
    ]
    |> Enum.each(fn {sql, params} -> Store.raw_execute(sql, params) end)

    File.rm_rf(workspace_id)
  end

  defp evaluation_probes(state) do
    workspace_id = "default:reality-eval-#{System.unique_integer([:positive])}"

    dataset_path =
      Path.join(
        System.tmp_dir!(),
        "optimal-reality-eval-#{System.unique_integer([:positive])}.jsonl"
      )

    seed =
      with {:ok, run} <-
             Evaluation.record_run(
               workspace_id: workspace_id,
               benchmark_name: "reality_recall_eval",
               dataset_name: "reality-small",
               dataset_size: 2,
               question_count: 2,
               answer_model: "rule-answer",
               judge_model: "rule-judge",
               judge_strategy: "deterministic",
               retrieval_top_k: 10,
               run_config: %{answer_temperature: 0},
               retrieval_config: %{package_type: "context_package"},
               judge_config: %{votes: 1}
             ),
           {:ok, _case_1} <-
             Evaluation.record_case(run.id,
               case_id: "case-1",
               question: "What was approved?",
               actual_answer: "The launch was approved.",
               expected_answer: "The launch was approved.",
               scores: %{accuracy: 1.0, grounding: 1.0},
               status: "passed"
             ),
           {:ok, _case_2} <-
             Evaluation.record_case(run.id,
               case_id: "case-2",
               question: "What was the unknown budget?",
               actual_answer: "Unknown.",
               scores: %{accuracy: 0.0, grounding: 0.5},
               status: "failed"
             ),
           {:ok, summary} <- Evaluation.summarize(run.id) do
        {:ok, %{run: run, summary: summary}}
      end

    state =
      case seed do
        {:ok, ctx} ->
          state
          |> probe("evaluation run persisted", fn ->
            case Store.raw_query(
                   "SELECT COUNT(*) FROM evaluation_runs WHERE workspace_id = ?1 AND id = ?2",
                   [workspace_id, ctx.run.id]
                 ) do
              {:ok, [[1]]} -> {:ok, "stored"}
              other -> {:error, inspect(other)}
            end
          end)
          |> probe("evaluation cases summarized", fn ->
            accuracy = get_in(ctx.summary, [:aggregate_scores, "accuracy", :average])

            if ctx.summary.case_count == 2 and ctx.summary.passed_count == 1 and accuracy == 0.5 do
              {:ok, "cases=2 accuracy=0.5"}
            else
              {:error, inspect(ctx.summary)}
            end
          end)

        {:error, reason} ->
          probe(state, "evaluation record seed", fn -> {:error, inspect(reason)} end)
      end

    state =
      state
      |> probe("evaluation dataset runner", fn ->
        with :ok <- seed_evaluation_dataset_memory(workspace_id),
             :ok <-
               File.write(dataset_path, [
                 Jason.encode!(%{
                   "question_id" => "dataset-case-1",
                   "question" => "approved",
                   "expected_answer" => "launch was approved"
                 }),
                 "\n"
               ]),
             {:ok, result} <-
               Evaluation.run_dataset(dataset_path,
                 workspace_id: workspace_id,
                 benchmark_name: "reality_dataset_eval",
                 retrieval_opts: [
                   allowed_partitions: ["reality-check"],
                   allowed_security_labels: ["internal"]
                 ]
               ) do
          if result.summary.case_count == 1 and result.summary.passed_count == 1 do
            {:ok, "jsonl cases=#{result.summary.case_count} passed=#{result.summary.passed_count}"}
          else
            {:error, inspect(result.summary)}
          end
        else
          {:error, reason} -> {:error, inspect(reason)}
          other -> {:error, inspect(other)}
        end
      end)

    File.rm(dataset_path)
    cleanup_evaluation_probe(workspace_id)
    state
  end

  defp seed_evaluation_dataset_memory(workspace_id) do
    source =
      OptimalEngine.MemoryCore.source_package_from_text(
        "The launch was approved after final review.",
        workspace_id: workspace_id,
        source_type: "meeting_note",
        security_labels: ["internal"],
        partition_ids: ["reality-check"]
      )

    with {:ok, claim} <-
           OptimalEngine.MemoryCore.extract_claim(source,
             claim_text: "The launch was approved after final review.",
             subject_anchor: "launch",
             action_class: "approval",
             aggregate_confidence: 0.95,
             aggregate_precision: 0.9
           ),
         {:ok, fact} <-
           OptimalEngine.MemoryCore.promote_claim_to_fact(claim,
             fact_text: "The launch was approved.",
             aggregate_confidence: 0.96,
             aggregate_precision: 0.92
           ),
         {:ok, _memory} <-
           OptimalEngine.MemoryCore.build_memory_object(fact,
             summary: "The launch approval unblocked the release plan."
           ) do
      :ok
    end
  end

  defp cleanup_evaluation_probe(workspace_id) do
    [
      {"DELETE FROM evaluation_runs WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM context_packages WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM relationship_edges WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM derivation_ledger WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM memory_objects WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM facts WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM claims WHERE workspace_id = ?1", [workspace_id]},
      {"DELETE FROM source_packages WHERE workspace_id = ?1", [workspace_id]}
    ]
    |> Enum.each(fn {sql, params} -> Store.raw_execute(sql, params) end)
  end

  defp wiki_probes(state) do
    ensure_reality_wiki_page()

    state
    |> probe("Wiki.list(default tenant)", fn ->
      case Wiki.list("default") do
        {:ok, pages} -> {:ok, "#{length(pages)} pages"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("Wiki.latest(customer-portal-pricing-decision)", fn ->
      case Wiki.latest("default", "customer-portal-pricing-decision", "default") do
        {:ok, page} -> {:ok, "v#{page.version}, #{byte_size(page.body)} bytes"}
        err -> {:warn, inspect(err)}
      end
    end)
    |> probe("Wiki.verify (integrity on that page)", fn ->
      case Wiki.latest("default", "customer-portal-pricing-decision", "default") do
        {:ok, page} ->
          report = Wiki.verify(page)
          {:ok, "ok?=#{report.ok?} issues=#{length(report.issues)}"}

        _ ->
          {:warn, "no page"}
      end
    end)
  end

  defp ensure_reality_wiki_page do
    case Wiki.latest("default", "customer-portal-pricing-decision", "default") do
      {:ok, _page} ->
        :ok

      {:error, :not_found} ->
        Wiki.put(%Page{
          tenant_id: "default",
          workspace_id: "default",
          slug: "customer-portal-pricing-decision",
          audience: "default",
          version: 1,
          frontmatter: %{"seeded_by" => "optimal.reality_check"},
          body: "# Customer Portal Pricing Decision\n\n## Summary\nSeed page for reality check.\n",
          curated_by: "optimal.reality_check"
        })

      _other ->
        :ok
    end
  end

  defp retrieval_probes(state) do
    receiver = Receiver.new(%{format: :markdown, bandwidth: :medium})

    state
    |> probe("RAG.ask simple ('pricing')", fn ->
      {:ok, res} = Retrieval.ask("pricing", receiver: receiver, skip_intent: true)

      {:ok,
       "source=#{res.source} delivered=#{res.trace.n_delivered} elapsed=#{res.trace.elapsed_ms}ms"}
    end)
    |> probe("RAG.ask complex (long natural query)", fn ->
      q =
        "customer pricing decision Q4 customer portal partner renewal pipeline advanced track curriculum"

      {:ok, res} = Retrieval.ask(q, receiver: receiver, skip_intent: true)

      {:ok,
       "source=#{res.source} delivered=#{res.trace.n_delivered} elapsed=#{res.trace.elapsed_ms}ms"}
    end)
    |> probe("RAG.ask empty query (edge)", fn ->
      {:ok, res} = Retrieval.ask("", receiver: receiver, skip_intent: true, skip_wiki: true)
      {:ok, "source=#{res.source} delivered=#{res.trace.n_delivered}"}
    end)
    |> probe("RAG.ask junk tokens (no-match)", fn ->
      {:ok, res} =
        Retrieval.ask("zzxqyw fnord #{System.unique_integer([:positive])}",
          receiver: receiver,
          skip_intent: true,
          skip_wiki: true
        )

      {:ok, "source=#{res.source} (expected :empty or :chunks)"}
    end)
    |> probe("WikiFirst.lookup_many('customer portal')", fn ->
      pages = Retrieval.WikiFirst.lookup_many("customer portal", "default")
      {:ok, "#{length(pages)} matching pages"}
    end)
    |> probe("direct search → 5 hits, principal=nil", fn ->
      case Retrieval.search("platform", limit: 5) do
        {:ok, hits} -> {:ok, "#{length(hits)} hits"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("receiver bandwidth → token budget math", fn ->
      small = Receiver.new(%{bandwidth: :small})
      large = Receiver.new(%{bandwidth: :large})
      {:ok, "small=#{small.token_budget} large=#{large.token_budget}"}
    end)
  end

  defp compliance_probes(state) do
    # Create a throwaway principal so we don't mutate real data.
    suffix = System.unique_integer([:positive])
    pid = "user:reality-check-#{suffix}@test"

    {:ok, _} =
      OptimalEngine.Identity.Principal.upsert(%{
        id: pid,
        kind: :user,
        display_name: "Reality Check #{suffix}"
      })

    state
    |> probe("Compliance.scan_pii", fn ->
      matches =
        Compliance.scan_pii("Reach me at rc@example.com or 415-555-0100. Card 4532015112830366.")

      {:ok, "#{length(matches)} matches: #{Enum.map_join(matches, ",", & &1.kind)}"}
    end)
    |> probe("Compliance.redact (mask strategy)", fn ->
      report =
        Compliance.redact("Email rc@example.com · SSN 123-45-6789", strategy: :mask)

      {:ok, "#{length(report.matches)} matches, body=#{byte_size(report.redacted)}b"}
    end)
    |> probe("Compliance.dsar_export(#{pid})", fn ->
      case Compliance.dsar_export(pid) do
        {:ok, export} -> {:ok, "#{map_size(export)} sections"}
        err -> {:error, inspect(err)}
      end
    end)
    |> probe("Compliance.erasure_preview(#{pid})", fn ->
      case Compliance.erasure_preview(pid) do
        {:ok, preview} ->
          {:ok, "counts=#{Enum.map_join(preview.counts, ",", fn {k, v} -> "#{k}:#{v}" end)}"}

        err ->
          {:error, inspect(err)}
      end
    end)
    |> probe("Compliance.active_legal_holds (empty)", fn ->
      holds = Compliance.active_legal_holds("default")
      {:ok, "#{length(holds)} active"}
    end)
    |> probe("Compliance.retention_sweep --dry-run", fn ->
      case Compliance.retention_sweep(dry_run: true) do
        {:ok, result} ->
          {:ok,
           "policies=#{result.policies_evaluated} skipped_held=#{result.skipped_held} errors=#{result.errors}"}

        err ->
          {:error, inspect(err)}
      end
    end)
  end

  # ─── probe harness ──────────────────────────────────────────────────────

  defp probe(state, label, fun) do
    t0 = System.monotonic_time(:millisecond)

    {status, detail} =
      try do
        case fun.() do
          {:ok, d} -> {:ok, d}
          {:warn, d} -> {:warn, d}
          {:error, d} -> {:error, d}
          other -> {:error, inspect(other)}
        end
      rescue
        e -> {:error, "raised: #{Exception.message(e)}"}
      catch
        kind, reason -> {:error, "caught #{kind}: #{inspect(reason)}"}
      end

    elapsed = System.monotonic_time(:millisecond) - t0
    tag = format_tag(status)

    IO.puts("    #{tag}  #{String.pad_trailing(label, 50)} #{format_elapsed(elapsed)} · #{detail}")

    %{state | probes: [{label, status, elapsed, detail} | state.probes]}
  end

  defp format_tag(:ok), do: IO.ANSI.green() <> "OK  " <> IO.ANSI.reset()
  defp format_tag(:warn), do: IO.ANSI.yellow() <> "WARN" <> IO.ANSI.reset()
  defp format_tag(:error), do: IO.ANSI.red() <> "FAIL" <> IO.ANSI.reset()

  defp format_elapsed(ms) do
    str = String.pad_leading("#{ms}ms", 7)

    cond do
      ms < 10 -> IO.ANSI.faint() <> str <> IO.ANSI.reset()
      ms < 200 -> str
      ms < 1000 -> IO.ANSI.yellow() <> str <> IO.ANSI.reset()
      true -> IO.ANSI.red() <> str <> IO.ANSI.reset()
    end
  end

  defp summarize(%{probes: probes, started: t0} = _state) do
    total = System.monotonic_time(:millisecond) - t0
    counts = Enum.frequencies_by(probes, fn {_, s, _, _} -> s end)
    ok = Map.get(counts, :ok, 0)
    warn = Map.get(counts, :warn, 0)
    fail = Map.get(counts, :error, 0)

    slowest =
      probes
      |> Enum.sort_by(fn {_, _, ms, _} -> ms end, :desc)
      |> Enum.take(5)

    IO.puts("\n  ─ Summary " <> String.duplicate("─", 55))
    IO.puts("    total probes: #{length(probes)}   ok: #{ok}   warn: #{warn}   fail: #{fail}")
    IO.puts("    wall-clock:   #{total}ms\n")

    IO.puts("    slowest 5:")

    Enum.each(slowest, fn {label, _s, ms, _d} ->
      IO.puts("      #{format_elapsed(ms)}  #{label}")
    end)

    IO.puts("\n└──────────────────────────────────────────────────────────────┘\n")

    if fail > 0 do
      IO.puts(
        IO.ANSI.red() <> "Reality check: #{fail} failures. See FAIL lines above." <> IO.ANSI.reset()
      )

      System.halt(1)
    end
  end
end

defmodule Mix.Tasks.Optimal.RealityCheck.ConnectorAssetAdapter do
  @moduledoc false

  @behaviour OptimalEngine.Connectors.Behaviour

  alias OptimalEngine.Connectors.Transform

  @impl true
  def kind, do: :slack

  @impl true
  def display_name, do: "Reality Connector Asset Adapter"

  @impl true
  def auth_scheme, do: :token

  @impl true
  def required_config_keys, do: []

  @impl true
  def init(config), do: {:ok, config}

  @impl true
  def sync(_state, _cursor) do
    signal =
      Transform.new_signal(%{
        id: Transform.signal_id(:slack, "reality-msg-1"),
        title: "Reality connector file payload",
        content: "Reality connector file payload",
        path: "optimal://connectors/slack/reality-msg-1",
        node: "inbox"
      })

    payload = %{
      "id" => "reality-msg-1",
      "attachments" => [
        %{
          "id" => "reality-file-1",
          "filename" => "reality.txt",
          "content_type" => "text/plain",
          "content_base64" => Base.encode64("reality connector asset evidence")
        }
      ]
    }

    {:ok, %{signals: [signal], cursor: "reality-cursor-next", payloads: [payload]}}
  end

  @impl true
  def transform(_payload), do: {:error, :not_used}
end
