# Generates priv/genres.exs from the OptimalOS genre templates.
# Run: elixir scripts/gen_genre_registry.exs <templates_dir> <out_file>
# One-shot tooling. The produced priv/genres.exs is the canonical registry
# shipped inside the engine repo (self-contained, no runtime dep on OptimalOS).

[templates_dir, out_file] =
  case System.argv() do
    [d, o] -> [d, o]
    _ ->
      templates =
        System.get_env("OPTIMAL_GENRE_TEMPLATES_DIR") ||
          Path.expand("../../docs/taxonomy/genres", __DIR__)

      [templates, "priv/genres.exs"]
  end

slug = fn name ->
  name
  |> String.trim()
  |> String.downcase()
  |> String.replace(~r/[^a-z0-9]+/, "-")
  |> String.trim("-")
end

parse_signal_type = fn raw ->
  # Pull the first `:atom` mentioned, default :inform
  case Regex.run(~r/`:(\w+)`/, raw || "") do
    [_, t] -> t
    _ -> "inform"
  end
end

parse_mode = fn raw ->
  case Regex.run(~r/`:(\w+)`/, raw || "") do
    [_, m] -> m
    _ -> "linguistic"
  end
end

parse_template = fn path ->
  content = File.read!(path)

  prop = fn key ->
    case Regex.run(~r/\|\s*\*\*#{key}\*\*\s*\|\s*(.+?)\s*\|/, content) do
      [_, v] -> String.trim(v)
      _ -> nil
    end
  end

  genre =
    case Regex.run(~r/^###\s+`([^`]+)`/m, content) do
      [_, g] -> g
      _ -> Path.basename(path, ".md")
    end

  category = prop.("Category") || "Operational"
  signal_type = parse_signal_type.(prop.("Signal type"))
  mode = parse_mode.(prop.("Typical mode"))
  purpose = prop.("Purpose") || ""

  # Skeleton: rows of the last markdown table. Capture section names where Status is [R] or [O].
  sections =
    Regex.scan(~r/^\|\s*\d+\s*\|\s*([^|]+?)\s*\|\s*\[([RO])\]\s*\|/m, content)
    |> Enum.map(fn [_, section, status] ->
      %{name: String.trim(section), required: status == "R"}
    end)

  %{
    genre: genre,
    category: String.downcase(category),
    signal_type: signal_type,
    mode: mode,
    purpose: purpose,
    sections: sections
  }
end

genres =
  templates_dir
  |> Path.join("**/*.md")
  |> Path.wildcard()
  |> Enum.reject(&(Path.basename(&1) |> String.downcase() |> String.starts_with?("readme")))
  |> Enum.map(parse_template)
  |> Enum.reject(&(&1.genre == "" or is_nil(&1.genre)))
  |> Enum.uniq_by(& &1.genre)
  |> Enum.sort_by(& &1.genre)

# Emit a plain Elixir term (list of maps) for Code.eval at load time.
body = inspect(genres, limit: :infinity, printable_limit: :infinity, pretty: true)

header = """
# AUTO-GENERATED by scripts/gen_genre_registry.exs from the OptimalOS genre
# taxonomy (docs/taxonomy/genres). This is the SINGLE canonical genre registry
# for the engine. #{length(genres)} genres. Do not edit by hand; regenerate.
"""

File.write!(out_file, header <> body <> "\n")
IO.puts("Wrote #{length(genres)} genres to #{out_file}")
